import type { Exercise, ProgramDef, ProtocolItem } from './types'

/**
 * Durability strength — built from `docs/research/durability-cardio.md`
 * (blocks A–D). One ongoing phase plus a deload phase; the old heavy /
 * small-joint / daily grouping is expressed per-item through `frequency`
 * (2×/wk heavy, 2–3×/wk small-joint, daily balance and isometrics) rather
 * than through phases.
 *
 * The tibialis-anterior and wrist/finger micro-doses from the research doc's
 * Block C live in the `tibant`, `wrist` and `fingers` programs, not here.
 */

export const strengthExercises: Record<string, Exercise> = {
  // ── Block A — lower body (PFPS-safe selection) ──────────────────────
  'goblet-box-squat': {
    id: 'goblet-box-squat',
    name: 'Goblet Squat to Box',
    targetArea: 'Quads · glutes',
    cue: 'Sit back to the box, chest tall — the box tells you where to stop.',
    instructions:
      'Hold a dumbbell or kettlebell at the chest and sit back to a box set so the knee bends about 50–60°. Pause on the box, then drive up.',
    whyItMatters:
      'Depth is the patellofemoral dial. A box fixes the knee angle so you can load the squat pattern heavily without loading the painful range.',
    contextTag: 'gym',
    equipment: ['dumbbell', 'kettlebell', 'box'],
    commonMistakes: [
      'Dropping onto the box instead of controlling down',
      'Letting the knees cave inward',
      'Going deeper than the box out of habit',
    ],
    progression: 'Heavier bell → lower box (only if pain-free) → barbell front squat.',
    regression: 'Higher box, bodyweight only, or swap to the Spanish squat isometric.',
  },
  'dumbbell-rdl': {
    id: 'dumbbell-rdl',
    name: 'Dumbbell Romanian Deadlift',
    targetArea: 'Hamstrings · glutes',
    cue: 'Push your hips back to the wall behind you.',
    instructions:
      'Dumbbells at the thighs, soft knees. Push the hips back with a flat back until you feel a hamstring stretch around mid-shin, then drive the hips forward.',
    whyItMatters:
      'Trains the posterior chain at length — the deceleration cable that keeps hamstrings from tearing on a sprint back down the floor. Hip-dominant, so it is PFPS-safe backbone work.',
    contextTag: 'gym',
    equipment: ['dumbbell', 'kettlebell'],
    commonMistakes: [
      'Squatting instead of hinging',
      'Rounding the low back',
      'Going deeper than hamstring flexibility allows',
    ],
    progression: 'Heavier, then single-leg RDL.',
    regression: 'Shorter range, hands sliding down the thighs, or a band-resisted hip hinge.',
  },
  'split-squat-short-stride': {
    id: 'split-squat-short-stride',
    name: 'Short-Stride Split Squat',
    targetArea: 'Quads · glutes',
    cue: 'Front shin vertical, back knee straight down.',
    instructions:
      'Rear foot on a low 4–8" step (not a bench), stride short enough that the front shin stays close to vertical. Lower with control and drive through the front heel.',
    whyItMatters:
      'Single-leg strength and hip control are the foundation of changing direction hard without blowing a knee.',
    contextTag: 'gym',
    equipment: ['step', 'dumbbell'],
    commonMistakes: [
      'Stride too long — the hip flexor stretch takes over',
      'Stride too short — the front knee travels forward, bad for PFPS',
      'Torso collapsing forward',
    ],
    progression: 'Dumbbells → deeper range → higher rear foot.',
    regression: 'Both feet on the floor (static lunge), hand on a wall, less depth.',
  },
  'step-down-eccentric': {
    id: 'step-down-eccentric',
    name: 'Eccentric Step-Down',
    targetArea: 'Quads · patellar tendon',
    cue: "Lower like you're placing an egg on the floor — 4 seconds down.",
    instructions:
      'Stand on a step on one leg and slowly lower the opposite heel toward the floor, tap, and return. The height at which this stays pain-free is your current tolerance for knee flexion under load.',
    whyItMatters:
      'Loads the patellar tendon and trains the knee to absorb landing force in the exact position it usually gives out. Doubles as the PFPS gatekeeper test.',
    contextTag: 'gym',
    equipment: ['step', 'dumbbell'],
    commonMistakes: [
      'Dropping fast',
      'Pushing off the down leg',
      'Letting the standing knee drift inward',
    ],
    progression: 'Taller step → hold dumbbells → slower tempo.',
    regression: '2" step, hold a rail, or switch to the short-stride split squat.',
  },
  'hip-thrust': {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    targetArea: 'Glutes',
    cue: 'Ribs down, finish with the glutes, not the low back.',
    instructions:
      'Upper back on a bench or couch edge, feet flat, load across the hips. Drive the hips to full extension, squeeze the glutes, lower under control.',
    whyItMatters:
      'The heaviest glute loading available with essentially zero patellofemoral cost — PFPS-safe backbone work that never needs substituting.',
    contextTag: 'gym',
    equipment: ['bench', 'dumbbell', 'band'],
    commonMistakes: [
      'Hyperextending the lumbar spine at the top',
      'Heels too far forward, turning it into a hamstring exercise',
      'Short range',
    ],
    progression: 'Barbell with a pad → single-leg.',
    regression: 'Floor glute bridge, band across the hips.',
  },
  'nordic-hamstring-curl': {
    id: 'nordic-hamstring-curl',
    name: 'Nordic Hamstring Curl',
    targetArea: 'Hamstrings · eccentric',
    cue: 'Resist all the way down — the goal is to fail slowly, not to fail late.',
    instructions:
      'Kneel with the ankles anchored, body straight from knees to head. Lower forward as slowly as possible, catch with the hands, push back up. Start at 2 × 4 and stay there for two weeks.',
    whyItMatters:
      'Meta-analysis of 8,459 athletes puts hamstring strain rate roughly halved when programs include it — though a later reappraisal calls the effect inconclusive. Cheap and low-risk either way.',
    contextTag: 'floor',
    equipment: ['mat', 'nordic-anchor', 'band'],
    commonMistakes: [
      'Hinging at the hips and breaking the straight line',
      'Dropping fast',
      'Doing too many too soon — this exercise produces serious DOMS',
    ],
    progression: 'Less band assist → longer eccentric → more reps.',
    regression: 'Heavy band assist, hands on a raised surface, or Swiss-ball leg curls.',
  },
  'copenhagen-plank': {
    id: 'copenhagen-plank',
    name: 'Copenhagen Adductor Plank',
    targetArea: 'Adductors',
    cue: 'Squeeze the bench with the top leg.',
    instructions:
      "Side-lying with the top leg's inner ankle or knee resting on a bench. Lift the hips and bottom leg into a straight line and hold.",
    whyItMatters:
      'Groin strains come from the adductors being asked to decelerate a lateral push they were never loaded for. This is the cheapest insurance against that.',
    contextTag: 'floor',
    equipment: ['bench', 'mat'],
    commonMistakes: [
      'Letting the hips sag or rotate back',
      'Starting with the long-lever ankle-supported version',
    ],
    progression: 'Knee-supported → ankle-supported → add reps or a dynamic version.',
    regression: 'Bottom knee on the floor, shorter holds.',
  },
  'band-lateral-walk': {
    id: 'band-lateral-walk',
    name: 'Banded Lateral Walk',
    targetArea: 'Glute medius',
    cue: 'Push the band apart the whole way.',
    instructions:
      'Mini band above the knees, quarter-squat stance, step sideways keeping tension on the band. Do not let the feet click together.',
    whyItMatters:
      'Hip abductor strengthening is the best-supported half of PFPS treatment, and the glute medius is what stops the knee caving on a cut.',
    contextTag: 'standing',
    equipment: ['mini-band'],
    commonMistakes: [
      'Standing too upright',
      'Letting the trailing foot drag in',
      'Band too light to matter',
    ],
    progression: 'Heavier band, band at the ankles, more steps.',
    regression: 'Lighter band, fewer steps.',
  },
  'side-plank-hip-abduction': {
    id: 'side-plank-hip-abduction',
    name: 'Side Plank with Top-Leg Abduction',
    targetArea: 'Glute medius · trunk',
    cue: 'Lead with the heel, not the toe.',
    instructions:
      'Forearm side plank. Lift the top leg toward the ceiling with the toe turned slightly down, then lower with control.',
    whyItMatters:
      'Combines the hip abductor work PFPS responds to with the lateral trunk stiffness that keeps the pelvis level on one leg.',
    contextTag: 'floor',
    equipment: ['mat', 'ankle-weight'],
    commonMistakes: ['Rotating the pelvis backward', 'Hiking the hip'],
    progression: 'Ankle band or ankle weight, longer holds.',
    regression: 'Bottom knee down, or side-lying clamshell.',
  },
  'sled-push-or-incline-carry': {
    id: 'sled-push-or-incline-carry',
    name: 'Sled Push / Heavy Incline Carry',
    targetArea: 'Whole lower body',
    cue: 'Long, driving steps — lean into it from the ankle, not the waist.',
    instructions:
      'Push a loaded sled 20–30 m at a hard but steady pace, or walk a steep treadmill at 3.0 mph wearing a weight vest.',
    whyItMatters:
      'Concentric-only heavy lower-body work: high effort, almost no soreness cost. The one hard leg piece that does not eat into the next sport day.',
    contextTag: 'sweat',
    equipment: ['sled', 'treadmill', 'weight-vest'],
    commonMistakes: ['Choppy short steps', 'Loading so heavy it becomes a grind'],
    progression: 'More load or more distance.',
    regression: 'Lighter, shorter. Skip entirely while the anterior tibialis is symptomatic.',
  },

  // ── Block B — upper body and trunk (wrist-safe) ─────────────────────
  'neutral-grip-db-floor-press': {
    id: 'neutral-grip-db-floor-press',
    name: 'Neutral-Grip Dumbbell Floor Press',
    targetArea: 'Chest · triceps',
    cue: 'Elbows at 45 degrees, wrists stacked over elbows.',
    instructions:
      'Lying on the floor, dumbbells with palms facing each other. Press up, then lower until the triceps touch the floor. The floor deliberately limits the range.',
    whyItMatters:
      'The wrist-safe default for all pressing: a neutral grip means no loaded wrist extension, which is the exact thing an irritable wrist cannot tolerate.',
    contextTag: 'floor',
    equipment: ['dumbbell', 'mat'],
    commonMistakes: [
      'Letting the wrist bend back — the exact thing you are avoiding',
      'Flaring the elbows to 90°',
    ],
    progression: 'Heavier, then dumbbell bench press for the fuller range.',
    regression: 'Lighter, one arm at a time.',
  },
  'push-up-parallettes': {
    id: 'push-up-parallettes',
    name: 'Push-Up on Parallettes',
    targetArea: 'Chest · trunk',
    cue: 'Squeeze your glutes — one straight line from ears to heels.',
    instructions:
      'Hands on parallettes or hex dumbbell handles so the wrist stays neutral. Body in a straight line, lower the chest to handle level.',
    whyItMatters:
      'The wrist-safe replacement for floor push-ups — the handles keep the wrist out of loaded extension entirely.',
    contextTag: 'floor',
    equipment: ['parallettes', 'dumbbell', 'mat'],
    commonMistakes: ['Sagging hips', 'Flaring elbows', 'Letting the head lead'],
    progression: 'Hands lower → feet elevated → add pauses.',
    regression: 'Hands on a countertop or bench.',
  },
  'half-kneeling-landmine-press': {
    id: 'half-kneeling-landmine-press',
    name: 'Half-Kneeling Landmine Press',
    targetArea: 'Shoulders · trunk',
    cue: 'Ribs down, press *away*, not straight up.',
    instructions:
      'Half-kneeling with the inside knee up on the pressing side, barbell end at the shoulder. Press up and forward along the arc of the bar.',
    whyItMatters:
      'The overhead-press substitute that keeps the wrist neutral and the shoulder out of the end-range positions a 49-year-old shoulder resents.',
    contextTag: 'gym',
    equipment: ['landmine', 'barbell'],
    commonMistakes: [
      'Leaning back to press',
      'Letting the front knee drift',
      'Gripping the bar too tightly',
    ],
    progression: 'More load, then standing.',
    regression: 'Lighter bar, two hands.',
  },
  'chest-supported-row-neutral': {
    id: 'chest-supported-row-neutral',
    name: 'Chest-Supported Neutral-Grip Row',
    targetArea: 'Upper back',
    cue: 'Pull with the elbow, pause when the dumbbells reach your ribs.',
    instructions:
      'Face-down on a 30–45° incline bench, dumbbells hanging with palms facing each other. Row to the ribs, pause, lower.',
    whyItMatters:
      'The wrist-safe replacement for barbell rows and pronated pull-ups, and the chest support removes the low-back cost of the pull.',
    contextTag: 'gym',
    equipment: ['bench', 'dumbbell'],
    commonMistakes: [
      'Using body english, which defeats the chest support',
      'Shrugging',
      'Short range',
    ],
    progression: 'Heavier, longer pause.',
    regression: 'Lighter, higher bench angle.',
  },
  'trx-row-neutral': {
    id: 'trx-row-neutral',
    name: 'TRX / Ring Row',
    targetArea: 'Upper back',
    cue: 'Body stays a plank the entire rep.',
    instructions:
      'Handles in a neutral grip, body straight, heels planted. Pull the chest to the hands. Walk the feet forward to make it harder.',
    whyItMatters:
      'Infinitely adjustable neutral-grip pulling — the best home option when the wrist rules out a bar.',
    contextTag: 'gym',
    equipment: ['trx'],
    commonMistakes: [
      'Hips sagging',
      'Pulling with the arms only',
      'Gripping so hard the forearm lights up — loosen the grip, hook the fingers',
    ],
    progression: 'Walk the feet forward (more horizontal), then elevate them.',
    regression: 'Walk the feet back (more upright).',
  },
  'band-pull-apart': {
    id: 'band-pull-apart',
    name: 'Band Pull-Apart',
    targetArea: 'Rear delts · mid-back',
    cue: 'Pull the band to your sternum, not your neck.',
    instructions:
      'Band at arm’s length in front, pull apart to the chest, squeeze the shoulder blades, return slowly.',
    whyItMatters:
      'Thirty seconds of upper-back work that keeps the shoulder balanced against all the pressing — and it is free of wrist load entirely.',
    contextTag: 'standing',
    equipment: ['band'],
    commonMistakes: ['Shrugging', 'Letting the band snap back'],
    progression: 'Heavier band, pause at end range.',
    regression: 'Lighter band, wider start grip.',
  },
  'face-pull-band': {
    id: 'face-pull-band',
    name: 'Band Face Pull',
    targetArea: 'Rear delts · external rotators',
    cue: 'Elbows high, thumbs back.',
    instructions:
      'Band anchored at eye height. Pull toward the face with the elbows high, rotating the hands so the thumbs finish pointing back.',
    whyItMatters:
      'External rotation under load is the shoulder-health item that keeps overhead shooting and serving comfortable into the fifties.',
    contextTag: 'standing',
    equipment: ['band'],
    commonMistakes: ['Turning it into a row', 'Anchoring the band too low'],
    progression: 'Heavier band, 2-second hold.',
    regression: 'Lighter band, drop the external rotation.',
  },
  'pallof-press': {
    id: 'pallof-press',
    name: 'Pallof Press',
    targetArea: 'Anti-rotation trunk',
    cue: "Don't let the band twist you.",
    instructions:
      'Band anchored at chest height to the side, hands at the sternum. Press straight out, resist the rotational pull, return.',
    whyItMatters:
      'Court sport is rotational. Training the trunk to *refuse* rotation is what lets the hips and shoulders separate without the low back paying for it.',
    contextTag: 'standing',
    equipment: ['band'],
    commonMistakes: [
      'Leaning away from the anchor',
      'Rushing',
      'Standing too close, so there is no tension',
    ],
    progression: 'Step further from the anchor, add a hold, half-kneeling or split stance.',
    regression: 'Lighter band, stand closer to the anchor.',
  },
  'dead-bug': {
    id: 'dead-bug',
    name: 'Dead Bug',
    targetArea: 'Anterior trunk',
    cue: 'Low back glued to the floor the whole time.',
    instructions:
      'On your back, arms up, hips and knees at 90°. Press the low back into the floor and extend the opposite arm and leg, then return.',
    whyItMatters:
      'Teaches the trunk to hold position while the limbs move — which is the entire job description of the trunk in basketball.',
    contextTag: 'floor',
    equipment: ['mat'],
    commonMistakes: [
      'Low back arching — the only failure mode that matters',
      'Moving too fast',
      'Holding the breath',
    ],
    progression: 'Straighten the extending leg fully, add a light weight or band.',
    regression: 'Extend only the leg or only the arm; shorten the range.',
  },
  'side-plank-forearm': {
    id: 'side-plank-forearm',
    name: 'Forearm Side Plank',
    targetArea: 'Lateral trunk',
    cue: 'Push the floor away with the forearm — long body.',
    instructions: 'Forearm and feet on the floor, body straight, hips lifted and level.',
    whyItMatters:
      'Lateral trunk endurance holds the pelvis level on one leg — and on the forearm it adds no wrist load at all.',
    contextTag: 'floor',
    equipment: ['mat'],
    commonMistakes: ['Sagging hips', 'Rotating forward'],
    progression: 'Longer holds, top leg lifted, feet stacked instead of staggered.',
    regression: 'Bottom knee down.',
  },
  'suitcase-carry': {
    id: 'suitcase-carry',
    name: 'Suitcase Carry',
    targetArea: 'Trunk · grip',
    cue: "Stand like the weight isn't there.",
    instructions: 'Heavy weight in one hand, walk tall for 30–40 m without leaning. Switch sides.',
    whyItMatters:
      'Loaded-carry work builds trunk stiffness under a real asymmetric load — but it is a maximal grip task, so it waits until the wrist is quiet.',
    contextTag: 'gym',
    equipment: ['dumbbell', 'kettlebell'],
    commonMistakes: ['Leaning away from the weight', 'Shrugging', 'Hurrying'],
    progression: 'Heavier, longer distance.',
    regression: 'Lighter, shorter. Deferred entirely while the wrist is symptomatic.',
  },

  // ── Block C — tendon micro-doses ────────────────────────────────────
  'calf-raise-straight-knee': {
    id: 'calf-raise-straight-knee',
    name: 'Straight-Knee Calf Raise (HSR)',
    targetArea: 'Gastroc · Achilles',
    cue: 'Six seconds a rep — count it out loud.',
    instructions:
      'Forefoot on a step edge, knee straight. Rise to full plantarflexion over about 3 s, hold 1 s, lower over about 3 s into a full stretch.',
    whyItMatters:
      'Heavy Slow Resistance is what actually changes tendon capacity — equal to eccentric-only protocols for Achilles tendinopathy at 12 and 52 weeks, with far better adherence. The tendon that ruptures is the one you never loaded.',
    contextTag: 'gym',
    equipment: ['step', 'dumbbell', 'weight-vest'],
    commonMistakes: [
      'Bouncing',
      'Cutting the top range',
      'Going too light — a 15RM load is not a bodyweight load',
    ],
    progression:
      'The HSR wave over 12 weeks: 3×15RM → 3×12RM → 4×10RM → 4×8RM → 4×6RM. Then single-leg with a loaded backpack.',
    regression: 'Two legs, flat ground, bodyweight.',
  },
  'seated-soleus-raise': {
    id: 'seated-soleus-raise',
    name: 'Seated Calf Raise',
    targetArea: 'Soleus',
    cue: 'Heels as high as they go — pause at the top.',
    instructions:
      'Seated with feet flat and weight resting across the knees, drive the heels up as high as possible, then lower slowly.',
    whyItMatters:
      'The soleus absorbs most of your running and landing load and is nearly always undertrained — and this is the best couch exercise in the program.',
    contextTag: 'couch',
    equipment: ['dumbbell'],
    commonMistakes: ['Short range', 'Too little weight across the knees'],
    progression: 'More weight, single leg, longer holds.',
    regression: 'Bodyweight only.',
  },
  'heel-drop-eccentric': {
    id: 'heel-drop-eccentric',
    name: 'Eccentric Heel Drop',
    targetArea: 'Achilles · remodeling',
    cue: 'Up with two, down with one, four seconds.',
    instructions:
      'Rise on two legs, shift onto one, and lower slowly off a step edge until the heel drops below the level of the step.',
    whyItMatters:
      'The classic Achilles remodeling dose. Lean on it if the tendon grumbles; it is the standing counterpart to the heavy slow calf raise.',
    contextTag: 'standing',
    equipment: ['step'],
    commonMistakes: ['Using both legs to lower', 'Not going below step level'],
    progression: 'Add a backpack; add a bent-knee version to bias the soleus.',
    regression: 'Both legs lowering, flat ground.',
  },
  'spanish-squat-isometric': {
    id: 'spanish-squat-isometric',
    name: 'Spanish Squat Isometric',
    targetArea: 'Quads · patellar tendon',
    cue: 'Shins vertical, let the band hold you back — sit into it.',
    instructions:
      'Heavy band around the backs of the knees anchored behind you. Sit back into about 60–70° of knee flexion with vertical shins and hold 45 s, resting 2 min between holds.',
    whyItMatters:
      'The isometric analgesic protocol reduced patellar tendon pain for ≥45 minutes in the original trial — but that was six volleyball players, and later work found responders and non-responders. Try it: if it helps, use it pre-sport; if not, lean on the HSR.',
    contextTag: 'standing',
    equipment: ['band', 'mini-band'],
    commonMistakes: [
      'Band too light, so it becomes a wall sit',
      'Leaning forward',
      'Letting the knees travel forward',
    ],
    progression: 'Longer holds → weight vest → convert to slow reps of 8–15.',
    regression: 'Wall sit.',
  },
  'wall-sit-isometric': {
    id: 'wall-sit-isometric',
    name: 'Wall Sit',
    targetArea: 'Quads',
    cue: 'Feet far enough out that the shins stay vertical.',
    instructions: 'Back against a wall, thighs approaching parallel, hold 30–45 s.',
    whyItMatters:
      'A no-equipment quad isometric you can do anywhere — though it reaches only about 60% of maximal quadriceps contraction, so it is a starting point rather than the endpoint.',
    contextTag: 'standing',
    equipment: [],
    commonMistakes: [
      'Feet too close to the wall, driving the knees forward and loading the kneecap',
      'Sliding down over time',
    ],
    progression: 'Longer holds, single leg, add a weight on the lap.',
    regression: 'Shallower angle, shorter holds.',
  },
  'knee-extension-isometric-band': {
    id: 'knee-extension-isometric-band',
    name: 'Seated Knee-Extension Isometric',
    targetArea: 'Quads · patellar tendon',
    cue: 'Hard but sustainable — you should be able to hold all 45 seconds.',
    instructions:
      'Seated in a chair, band around the ankle anchored behind. Push into about 60° of knee flexion at roughly 70% of max effort, hold 45 s, rest 2 min, five times.',
    whyItMatters:
      'The analgesic window runs about 45 minutes, so 10–20 minutes before sport it buys you a quieter knee for the first game — as long as you are not masking a tendon that is genuinely flaring.',
    contextTag: 'couch',
    equipment: ['band', 'ankle-weight'],
    commonMistakes: [
      'Going to 100% effort — unsustainable and provocative',
      'Holding the breath',
      'Too little rest between holds',
    ],
    progression: 'Heavier band, longer holds, then a leg-extension machine.',
    regression: 'Lighter band, 30 s holds.',
  },
  'ankle-eversion-band': {
    id: 'ankle-eversion-band',
    name: 'Banded Ankle Eversion / Inversion',
    targetArea: 'Peroneals',
    cue: 'Move the ankle, keep the knee still.',
    instructions:
      'Seated with a band around the forefoot, turn the sole outward against resistance for one set, then inward for a second. Give eversion the most work.',
    whyItMatters:
      'The peroneals on the outside of the shin actively stop the ankle rolling inward — the direct counterweight to the inversion sprain that is basketball’s most common injury.',
    contextTag: 'couch',
    equipment: ['band'],
    commonMistakes: ['Rotating the whole leg from the hip'],
    progression: 'Heavier band, slower tempo, more reps — then do it while balancing on that foot.',
    regression: 'Lighter band.',
  },

  // ── Block D — balance, proprioception, landing ──────────────────────
  'court-dynamic-warmup': {
    id: 'court-dynamic-warmup',
    name: '11+-Style Court Warm-Up',
    targetArea: 'Whole body · injury prevention',
    cue: "Warm up until you'd be happy to sprint, then start.",
    instructions:
      '8–12 min: 2–3 min easy jog; hip openers and closers; lateral shuffles both directions; walking lunges; 3–4 build-up strides to ~80%; 3–4 defensive slides or split-step drills; finish with two easy layup or dink sequences.',
    whyItMatters:
      'The single best-evidenced item in the whole program. FIFA 11+-style warm-ups cut knee injuries by about 46% and ankle injuries by about 33% in randomized trials — but only in the teams that actually did them before every session.',
    contextTag: 'sweat',
    equipment: ['court'],
    commonMistakes: [
      'Static stretching instead of dynamic movement',
      'Skipping it when you are late — that is exactly the day it matters',
      'Doing it at half effort',
    ],
    progression: 'Add the 11+ strength and plyo elements (planks, Nordics, hops) when you have five extra minutes.',
    regression: '5-minute version: jog, shuffles, strides, split-steps.',
  },
  'single-leg-balance-eyes-closed': {
    id: 'single-leg-balance-eyes-closed',
    name: 'Single-Leg Balance, Eyes Closed',
    targetArea: 'Proprioception',
    cue: 'Let the toes and ankle do the correcting — small adjustments, not big saves.',
    instructions:
      'Stand on one leg, barefoot, close your eyes and hold 30 s. Do it while brushing your teeth and while watching TV — that is the entire dosing strategy.',
    whyItMatters:
      'Proprioceptive training cuts ankle sprain rates by about a third, with the largest effect in people who have sprained before — NNT around 13 for recurrent sprains. The cheapest insurance in the program.',
    contextTag: 'standing',
    equipment: [],
    commonMistakes: [
      'Holding onto something, which defeats the purpose',
      'Locking the knee',
      'Giving up when it gets wobbly — the wobble *is* the training',
    ],
    progression: 'Foam pad or pillow → head turns → add a perturbation.',
    regression: 'Eyes open, fingertip on a wall.',
  },
  'single-leg-balance-perturbation': {
    id: 'single-leg-balance-perturbation',
    name: 'Single-Leg Balance with Perturbation',
    targetArea: 'Proprioception · reactive',
    cue: 'Eyes off your feet — track the ball.',
    instructions:
      'Single-leg stand while tossing a ball against a wall, turning the head side to side, or reaching with the free foot.',
    whyItMatters:
      'Games do not let you stare at your feet. Adding a distraction task is what makes the balance reflex available when your attention is on the play.',
    contextTag: 'standing',
    equipment: ['ball', 'foam-pad'],
    commonMistakes: ['Stiffening up', 'Staring at the floor'],
    progression: 'Unstable surface, eyes closed with head turns, one-handed catches.',
    regression: 'Two feet, or single leg with no perturbation.',
  },
  'y-balance-reach': {
    id: 'y-balance-reach',
    name: 'Y-Balance Reach',
    targetArea: 'Dynamic balance',
    cue: "Tap, don't plant.",
    instructions:
      'Balance on one leg and reach the other foot as far as possible forward, then back-and-in, then back-and-out, tapping lightly and returning without putting weight down.',
    whyItMatters:
      'Balance at the edges of your base of support, which is where the ankle actually gets rolled — not in the comfortable middle where static balance lives.',
    contextTag: 'floor',
    equipment: [],
    commonMistakes: ['Putting weight on the reaching foot', 'Letting the stance knee cave in'],
    progression: 'Further reaches, hold a light weight at the chest.',
    regression: 'Shorter reaches, fingertip support.',
  },
  'pogo-hops': {
    id: 'pogo-hops',
    name: 'Pogo Hops',
    targetArea: 'Achilles · ankle stiffness',
    cue: 'Stiff springs — minimize time on the ground, not maximize height.',
    instructions:
      'Small, fast, two-foot hops with stiff ankles and minimal knee bend, staying on the balls of the feet.',
    whyItMatters:
      'Excellent Achilles and tibialis-anterior stiffness training — but reintroduce it only once the tibialis is quiet. Power decays faster than strength after 45, and this is the cheapest way to keep it.',
    contextTag: 'standing',
    equipment: [],
    commonMistakes: ['Squatting between hops', 'Heels touching down', 'Going for height'],
    progression: 'Single-leg pogos, then forward and lateral travel.',
    regression: 'Fewer reps, lower amplitude, or on grass.',
  },
  'snapdown-stick': {
    id: 'snapdown-stick',
    name: 'Snap-Down to Stick Landing',
    targetArea: 'Landing mechanics',
    cue: 'Land quiet, freeze like a photograph.',
    instructions:
      'From a tall standing position, drop rapidly into an athletic quarter-squat landing position and freeze for 3 seconds.',
    whyItMatters:
      'Prevention programs that include plyometrics reduce ACL injury rates, and the mechanism is exactly this: rehearsing the absorb-and-stabilize moment until it is automatic.',
    contextTag: 'floor',
    equipment: ['mat'],
    commonMistakes: [
      'Landing loudly — that means joints are absorbing, not muscles',
      'Knees caving in',
      'Not actually holding the freeze',
    ],
    progression: 'Small box drop → single-leg snapdown.',
    regression: 'Slower, shallower, from a lower height.',
  },
  'lateral-bound-stick': {
    id: 'lateral-bound-stick',
    name: 'Lateral Bound with Stuck Landing',
    targetArea: 'Frontal-plane landing',
    cue: 'Land on a stable knee — if you wobble, you jumped too far.',
    instructions:
      'Push off one leg sideways, land on the opposite leg, stick and hold 2–3 s before the next rep.',
    whyItMatters:
      'Court injuries happen sideways. This loads the exact frontal-plane deceleration a defensive slide demands, under conditions where you control the distance.',
    contextTag: 'floor',
    equipment: [],
    commonMistakes: [
      'Bounding further than you can control',
      'Knee valgus on landing',
      'Rushing the reps',
    ],
    progression: 'Greater distance, then continuous bounds.',
    regression: 'Smaller distance, land on two feet.',
  },
  'single-leg-hop-hold': {
    id: 'single-leg-hop-hold',
    name: 'Single-Leg Hop and Hold',
    targetArea: 'Reactive landing',
    cue: 'Nose, knee, toe stacked on landing.',
    instructions: 'Hop forward on one leg, land on the same leg, stick and hold 3 s.',
    whyItMatters:
      'Games do not roll ankles in slow motion. This teaches the joint to absorb impact and stabilize instantly — the exact moment real sprains happen on cuts and landings.',
    contextTag: 'floor',
    equipment: [],
    commonMistakes: ['Letting the knee collapse inward', 'Hopping too far too soon'],
    progression: 'Longer hops, then hop-hop-stick sequences, then multidirectional.',
    regression: 'Two-foot takeoff with a single-leg landing, or shorter distance.',
  },
  'shuffle-decel-drill': {
    id: 'shuffle-decel-drill',
    name: 'Shuffle → Decelerate → Change Direction',
    targetArea: 'Deceleration',
    cue: 'Win the stop, not the start.',
    instructions:
      'Shuffle 5 m, decelerate to a complete stop in an athletic position, change direction, and repeat for 10–15 s.',
    whyItMatters:
      'Deceleration is where court injuries happen. This is deliberately practising the risky moment under conditions you control.',
    contextTag: 'sweat',
    equipment: ['court', 'cones'],
    commonMistakes: [
      'Rounding the change of direction instead of actually stopping',
      'Crossing the feet',
    ],
    progression: 'Longer distances, and reactive cues rather than pre-planned patterns.',
    regression: 'Slower, shorter, pre-planned only.',
  },
}

/**
 * The single ongoing phase. The old heavy / small-joint / daily split lives in
 * `frequency`: 2×/wk for heavy compounds, 2–3×/wk for band and trunk work,
 * daily for balance and tendon isometrics.
 */
const ongoingItems: ProtocolItem[] = [
  // ── (a) lower-body strength ───────────────────────────────────────
  {
    id: 'st-goblet-box-squat',
    exerciseId: 'goblet-box-squat',
    sets: 4,
    reps: 8,
    displayAmount: '6–10 reps',
    tempo: '3-1-1',
    load: 'Dumbbell or kettlebell; box at ~50–60° knee flexion',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    alternates: ['st-spanish-squat-isometric', 'st-split-squat-short-stride'],
    tissues: ['quads', 'glutes'],
    intensity: 'hard',
    notes:
      'Strength A opener. If the knee complains, raise the box first; if it still complains, prefer the Spanish squat isometric plus hip thrust — the PFPS-safe pair.',
  },
  {
    id: 'st-dumbbell-rdl',
    exerciseId: 'dumbbell-rdl',
    sets: 4,
    reps: 8,
    displayAmount: '6–10 reps',
    tempo: '3-1-1',
    load: 'Dumbbells or kettlebells, neutral grip',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    alternates: ['st-goblet-box-squat'],
    tissues: ['hamstrings', 'glutes'],
    intensity: 'hard',
    notes: 'Strength B opener — the hinge counterpart to the goblet squat.',
  },
  {
    id: 'st-split-squat-short-stride',
    exerciseId: 'split-squat-short-stride',
    sets: 3,
    reps: 9,
    displayAmount: '8–10 per leg',
    tempo: '3-0-1',
    load: 'Bodyweight → dumbbells; back foot on a low step',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    alternates: ['st-step-down-eccentric'],
    tissues: ['quads', 'glutes'],
    intensity: 'hard',
    notes: 'PFPS-safe variant of the split squat: short stride, vertical shin. If the front knee hurts, shorten the stride further and cut the depth.',
  },
  {
    id: 'st-step-down-eccentric',
    exerciseId: 'step-down-eccentric',
    sets: 3,
    reps: 8,
    displayAmount: '6–10 per leg',
    tempo: '4-0-1',
    load: '4–8" step, bodyweight → light dumbbells',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['L'],
    alternates: ['st-split-squat-short-stride'],
    tissues: ['quads', 'patellar-tendon'],
    intensity: 'hard',
    notes: 'PFPS gatekeeper — if provocative, drop to a 2" step or swap to the short-stride split squat.',
  },
  {
    id: 'st-hip-thrust',
    exerciseId: 'hip-thrust',
    sets: 3,
    reps: 10,
    displayAmount: '8–12 reps',
    tempo: '2-2-1',
    load: 'Barbell, dumbbell, or band; bench or couch edge',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    tissues: ['glutes', 'hamstrings'],
    intensity: 'hard',
    notes: 'PFPS-safe backbone — never needs substituting, so keep it when the squats get cut.',
  },
  {
    id: 'st-nordic-hamstring-curl',
    exerciseId: 'nordic-hamstring-curl',
    sets: 3,
    reps: 5,
    displayAmount: '4–6 reps',
    tempo: '4-0-X',
    load: 'Anchored feet + band assist or a partner',
    frequency: { perWeek: 2 },
    minSpacingDays: 3,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    tissues: ['hamstrings'],
    intensity: 'hard',
    notes: 'Start at 2 × 4 and stay there two weeks. Produces serious DOMS — 72h before the next hamstring session.',
  },
  {
    id: 'st-copenhagen-plank',
    exerciseId: 'copenhagen-plank',
    sets: 3,
    durationSeconds: 25,
    displayAmount: '15–30 s per side',
    tempo: 'isometric',
    load: 'Bench or couch for top-leg support',
    frequency: { perWeek: 2 },
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    tissues: ['glutes'],
    notes: 'Isometric — easy by R1, does not spend a hard day.',
  },
  {
    id: 'st-band-lateral-walk',
    exerciseId: 'band-lateral-walk',
    sets: 3,
    reps: 14,
    displayAmount: '12–15 steps per direction',
    tempo: '2-1-2',
    load: 'Mini loop band above the knees',
    frequency: { perWeek: 3 },
    bucket: 'quick',
    tissues: ['glutes'],
    notes: 'Also the standard opener for Strength A.',
  },
  {
    id: 'st-side-plank-hip-abduction',
    exerciseId: 'side-plank-hip-abduction',
    sets: 3,
    reps: 10,
    displayAmount: '8–12 per side',
    tempo: '2-2-2',
    load: 'Bodyweight → ankle band',
    frequency: { perWeek: 3 },
    bucket: 'quick',
    tissues: ['glutes', 'trunk'],
  },
  {
    id: 'st-sled-push-or-incline-carry',
    exerciseId: 'sled-push-or-incline-carry',
    sets: 4,
    durationSeconds: 30,
    displayAmount: '20–30 m or 30 s',
    tempo: 'continuous',
    load: 'Sled, or steep treadmill walk with a weight vest',
    frequency: { perWeek: 1 },
    minSpacingDays: 3,
    bucket: 'workout',
    workoutSizes: ['L'],
    tissues: ['quads', 'glutes', 'achilles-calf'],
    intensity: 'hard',
    notes: 'Optional. Skip entirely while the anterior tibialis is symptomatic (loaded dorsiflexion).',
  },

  // ── (b) upper body and trunk ──────────────────────────────────────
  {
    id: 'st-neutral-grip-db-floor-press',
    exerciseId: 'neutral-grip-db-floor-press',
    sets: 3,
    reps: 8,
    displayAmount: '6–10 reps',
    tempo: '3-1-1',
    load: 'Dumbbells, palms facing each other',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    alternates: ['st-push-up-parallettes', 'st-half-kneeling-landmine-press'],
    tissues: ['upper-push'],
    intensity: 'hard',
    notes: 'Wrist-safe default for pressing. Prefer this over any barbell bench or overhead press while the right wrist is symptomatic (R10).',
  },
  {
    id: 'st-push-up-parallettes',
    exerciseId: 'push-up-parallettes',
    sets: 3,
    reps: 10,
    displayAmount: '6–12 reps',
    tempo: '3-1-1',
    load: 'Parallettes or hex dumbbells',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    alternates: ['st-neutral-grip-db-floor-press'],
    tissues: ['upper-push'],
    intensity: 'hard',
    notes: 'Wrist-safe replacement for floor push-ups — prefer it whenever a flat-hand push-up bites (R10). Countertop hands work too.',
  },
  {
    id: 'st-half-kneeling-landmine-press',
    exerciseId: 'half-kneeling-landmine-press',
    sets: 3,
    reps: 8,
    displayAmount: '6–10 per side',
    tempo: '2-1-1',
    load: 'Landmine or barbell in a corner',
    frequency: { perWeek: 1 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    alternates: ['st-neutral-grip-db-floor-press'],
    tissues: ['upper-push', 'trunk'],
    intensity: 'hard',
    notes: 'Wrist-safe overhead substitute — prefer it over any barbell overhead press while the wrist is symptomatic.',
  },
  {
    id: 'st-chest-supported-row-neutral',
    exerciseId: 'chest-supported-row-neutral',
    sets: 3,
    reps: 10,
    displayAmount: '8–12 reps',
    tempo: '2-1-2',
    load: 'Dumbbells on an incline bench',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    alternates: ['st-trx-row-neutral'],
    tissues: ['upper-pull'],
    intensity: 'hard',
    notes: 'Wrist-safe replacement for pronated pull-ups and barbell rows (R10).',
  },
  {
    id: 'st-trx-row-neutral',
    exerciseId: 'trx-row-neutral',
    sets: 3,
    reps: 10,
    displayAmount: '8–12 reps',
    tempo: '2-1-2',
    load: 'TRX or rings; feet forward to set difficulty',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    alternates: ['st-chest-supported-row-neutral'],
    tissues: ['upper-pull'],
    intensity: 'hard',
    notes: 'Hook the fingers rather than gripping hard — a crushing grip lights up the forearm.',
  },
  {
    id: 'st-band-pull-apart',
    exerciseId: 'band-pull-apart',
    sets: 3,
    reps: 18,
    displayAmount: '15–20 reps',
    tempo: '2-1-2',
    load: 'Light resistance band',
    frequency: { perWeek: 3 },
    bucket: 'quick',
    tissues: ['upper-pull'],
    notes: 'Also the standard opener for Strength B.',
  },
  {
    id: 'st-face-pull-band',
    exerciseId: 'face-pull-band',
    sets: 3,
    reps: 15,
    displayAmount: '12–15 reps',
    tempo: '2-1-2',
    load: 'Band anchored at eye height',
    frequency: { perWeek: 3 },
    bucket: 'quick',
    tissues: ['upper-pull'],
  },
  {
    id: 'st-pallof-press',
    exerciseId: 'pallof-press',
    sets: 3,
    reps: 9,
    displayAmount: '8–10 per side',
    tempo: '2-2-2',
    load: 'Band anchored at chest height',
    frequency: { perWeek: 2 },
    bucket: 'quick',
    tissues: ['trunk'],
  },
  {
    id: 'st-dead-bug',
    exerciseId: 'dead-bug',
    sets: 3,
    reps: 9,
    displayAmount: '8–10 per side',
    tempo: '3-1-3',
    load: 'Bodyweight',
    frequency: { perWeek: 3 },
    bucket: 'quick',
    tissues: ['trunk'],
  },
  {
    id: 'st-side-plank-forearm',
    exerciseId: 'side-plank-forearm',
    sets: 3,
    durationSeconds: 30,
    displayAmount: '20–40 s per side',
    tempo: 'isometric',
    load: 'Bodyweight, on the forearm — no wrist load',
    frequency: { perWeek: 3 },
    bucket: 'quick',
    tissues: ['trunk'],
  },
  {
    id: 'st-suitcase-carry',
    exerciseId: 'suitcase-carry',
    sets: 3,
    displayAmount: '30–40 m per side',
    tempo: 'continuous',
    load: 'Heavy dumbbell or kettlebell',
    frequency: { perWeek: 1 },
    minSpacingDays: 3,
    bucket: 'workout',
    workoutSizes: ['L'],
    tissues: ['trunk', 'wrist-flexors'],
    intensity: 'hard',
    notes: 'Defer entirely while the wrist is acute (R10), and drop it from any week with 2+ pickleball sessions (R11).',
  },

  // ── (c) tendon micro-doses ────────────────────────────────────────
  {
    id: 'st-calf-raise-straight-knee',
    exerciseId: 'calf-raise-straight-knee',
    sets: 4,
    reps: 8,
    displayAmount: '6–15 reps (per HSR wave)',
    tempo: '3-0-3',
    load: 'Step edge; dumbbells, backpack, or barbell — heavy',
    frequency: { perWeek: 3 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    alternates: ['st-heel-drop-eccentric'],
    tissues: ['achilles-calf'],
    intensity: 'hard',
    notes: 'HSR counts as strength load (R13): non-consecutive days, inside the strength session.',
  },
  {
    id: 'st-seated-soleus-raise',
    exerciseId: 'seated-soleus-raise',
    sets: 3,
    reps: 12,
    displayAmount: '10–15 reps',
    tempo: '3-1-3',
    load: 'Weight or dumbbells across the knees — works on a couch',
    frequency: { perWeek: 4 },
    bucket: 'couch',
    tissues: ['achilles-calf'],
    notes: 'The best couch exercise in the program. Seated, so it never counts against a hard day.',
  },
  {
    id: 'st-heel-drop-eccentric',
    exerciseId: 'heel-drop-eccentric',
    sets: 3,
    reps: 13,
    displayAmount: '12–15 per side',
    tempo: '4-0-X',
    load: 'Bodyweight → backpack',
    frequency: { perWeek: 3 },
    minSpacingDays: 2,
    bucket: 'quick',
    alternates: ['st-calf-raise-straight-knee'],
    tissues: ['achilles-calf'],
    intensity: 'hard',
    notes:
      'Later phase — add once the heavy slow calf raise is established. Heavy eccentric loading: it spends a hard day and needs 48h from other Achilles work.',
  },
  {
    id: 'st-spanish-squat-isometric',
    exerciseId: 'spanish-squat-isometric',
    sets: 5,
    durationSeconds: 45,
    displayAmount: '5 × 45 s (2 min rest)',
    tempo: 'isometric',
    load: 'Heavy band around the knees, anchored behind',
    frequency: { perWeek: 'daily' },
    bucket: 'quick',
    alternates: ['st-wall-sit-isometric', 'st-knee-extension-isometric-band'],
    tissues: ['quads', 'patellar-tendon'],
    notes: 'Daily as needed (R12). Also the PFPS-safe stand-in when the goblet squat is provocative. Usable 10–20 min pre-sport for the analgesic window (R14).',
  },
  {
    id: 'st-wall-sit-isometric',
    exerciseId: 'wall-sit-isometric',
    sets: 5,
    durationSeconds: 40,
    displayAmount: '5 × 30–45 s',
    tempo: 'isometric',
    load: 'Wall only',
    frequency: { perWeek: 'daily' },
    bucket: 'quick',
    alternates: ['st-spanish-squat-isometric'],
    tissues: ['quads'],
    notes: 'Regression from the Spanish squat — use it when there is no band or anchor.',
  },
  {
    id: 'st-knee-extension-isometric-band',
    exerciseId: 'knee-extension-isometric-band',
    sets: 5,
    durationSeconds: 45,
    displayAmount: '5 × 45 s @ ~70% effort',
    tempo: 'isometric',
    load: 'Band or ankle weight, seated in a chair',
    frequency: { perWeek: 'daily' },
    bucket: 'couch',
    alternates: ['st-spanish-squat-isometric'],
    tissues: ['quads', 'patellar-tendon'],
    notes: 'Daily, and specifically 10–20 min before sport for the analgesic window (R14). Do not use it to mask a tendon that is actually flaring.',
  },
  {
    id: 'st-ankle-eversion-band',
    exerciseId: 'ankle-eversion-band',
    sets: 3,
    reps: 15,
    displayAmount: '15 per direction',
    tempo: '2-1-2',
    load: 'Light band, seated',
    frequency: { perWeek: 4 },
    bucket: 'couch',
    notes: 'Part of the daily couch protocol during the sports pause.',
  },

  // ── (d) balance, proprioception, landing ──────────────────────────
  {
    id: 'st-single-leg-balance-eyes-closed',
    exerciseId: 'single-leg-balance-eyes-closed',
    sets: 3,
    durationSeconds: 30,
    displayAmount: '30 s per leg',
    tempo: 'isometric',
    load: 'Barefoot on the floor',
    frequency: { perWeek: 'daily' },
    bucket: 'quick',
    alternates: ['st-single-leg-balance-perturbation'],
    notes: 'Brush-teeth and TV-time material. Daily is the dosing that produced the trial results.',
  },
  {
    id: 'st-single-leg-balance-perturbation',
    exerciseId: 'single-leg-balance-perturbation',
    sets: 3,
    durationSeconds: 40,
    displayAmount: '30–45 s per leg',
    tempo: 'continuous',
    load: 'Ball or light object; foam pad optional',
    frequency: { perWeek: 4 },
    bucket: 'quick',
    alternates: ['st-single-leg-balance-eyes-closed'],
    notes: 'Also the standard opener for Strength B.',
  },
  {
    id: 'st-y-balance-reach',
    exerciseId: 'y-balance-reach',
    sets: 3,
    reps: 5,
    displayAmount: '5 reaches per direction per leg',
    tempo: '3-0-3',
    load: 'Tape marks on the floor',
    frequency: { perWeek: 3 },
    bucket: 'quick',
  },
  {
    id: 'st-pogo-hops',
    exerciseId: 'pogo-hops',
    sets: 3,
    reps: 18,
    displayAmount: '15–20 hops',
    tempo: 'fast, minimal ground contact',
    load: 'Bodyweight',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'quick',
    tissues: ['achilles-calf', 'tibant-tendon'],
    intensity: 'hard',
    notes: 'Plyometric — counts as lower-body load (R8). Never the day before sport. Hold until the tibialis anterior is quiet.',
  },
  {
    id: 'st-snapdown-stick',
    exerciseId: 'snapdown-stick',
    sets: 3,
    reps: 5,
    displayAmount: '5 reps',
    tempo: 'fast down, 3 s hold',
    load: 'Bodyweight',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['L'],
    tissues: ['quads', 'achilles-calf'],
    intensity: 'hard',
    notes: 'Landing block — runs up front, after the warm-up and before the lifting. R8 applies.',
  },
  {
    id: 'st-lateral-bound-stick',
    exerciseId: 'lateral-bound-stick',
    sets: 3,
    reps: 5,
    displayAmount: '4–6 per side',
    tempo: 'explosive, 2–3 s hold',
    load: 'Bodyweight',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['L'],
    tissues: ['quads', 'glutes'],
    intensity: 'hard',
    notes: 'Landing block. R8 applies — never the day before sport.',
  },
  {
    id: 'st-single-leg-hop-hold',
    exerciseId: 'single-leg-hop-hold',
    sets: 3,
    reps: 4,
    displayAmount: '4–5 per side',
    tempo: 'explosive, 3 s hold',
    load: 'Bodyweight',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['L'],
    tissues: ['quads', 'achilles-calf'],
    intensity: 'hard',
    notes: 'Landing block. R8 applies.',
  },
  {
    id: 'st-shuffle-decel-drill',
    exerciseId: 'shuffle-decel-drill',
    sets: 5,
    durationSeconds: 13,
    displayAmount: '4–6 × 10–15 s',
    tempo: 'max effort, controlled stop',
    load: 'Court or driveway, cones',
    frequency: { perWeek: 1 },
    minSpacingDays: 3,
    bucket: 'workout',
    workoutSizes: ['L'],
    tissues: ['quads', 'hamstrings', 'tibant-tendon'],
    intensity: 'hard',
    notes: 'Backpedalling and hard lateral shuffling are the last movements to reintroduce after the tibialis anterior settles, not the first.',
  },
]

/**
 * Deload week — every 4th week, or reactively on 2+ overreaching signs (R25).
 * Strength volume down ~40% by dropping sets and keeping load; no plyometrics,
 * no new exercises. The daily easy work is unchanged.
 */
const deloadItems: ProtocolItem[] = [
  {
    id: 'dl-goblet-box-squat',
    exerciseId: 'goblet-box-squat',
    sets: 2,
    reps: 8,
    displayAmount: '2 × 6–10 reps',
    tempo: '3-1-1',
    load: 'Same load as the ongoing phase — drop sets, not weight',
    frequency: { perWeek: 1 },
    minSpacingDays: 3,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    alternates: ['dl-dumbbell-rdl'],
    tissues: ['quads', 'glutes'],
    intensity: 'hard',
  },
  {
    id: 'dl-dumbbell-rdl',
    exerciseId: 'dumbbell-rdl',
    sets: 2,
    reps: 8,
    displayAmount: '2 × 6–10 reps',
    tempo: '3-1-1',
    load: 'Same load — drop sets, not weight',
    frequency: { perWeek: 1 },
    minSpacingDays: 3,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    alternates: ['dl-goblet-box-squat'],
    tissues: ['hamstrings', 'glutes'],
    intensity: 'hard',
  },
  {
    id: 'dl-neutral-grip-db-floor-press',
    exerciseId: 'neutral-grip-db-floor-press',
    sets: 2,
    reps: 8,
    displayAmount: '2 × 6–10 reps',
    tempo: '3-1-1',
    load: 'Same load — drop sets, not weight',
    frequency: { perWeek: 1 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    tissues: ['upper-push'],
    intensity: 'hard',
  },
  {
    id: 'dl-chest-supported-row-neutral',
    exerciseId: 'chest-supported-row-neutral',
    sets: 2,
    reps: 10,
    displayAmount: '2 × 8–12 reps',
    tempo: '2-1-2',
    load: 'Same load — drop sets, not weight',
    frequency: { perWeek: 1 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    tissues: ['upper-pull'],
    intensity: 'hard',
  },
  {
    id: 'dl-calf-raise-straight-knee',
    exerciseId: 'calf-raise-straight-knee',
    sets: 2,
    reps: 8,
    displayAmount: '2 × 6–15 reps (HSR tempo)',
    tempo: '3-0-3',
    load: 'Hold the wave where it is — repeat last week rather than progressing',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    tissues: ['achilles-calf'],
    intensity: 'hard',
  },
  {
    id: 'dl-seated-soleus-raise',
    exerciseId: 'seated-soleus-raise',
    sets: 3,
    reps: 12,
    displayAmount: '10–15 reps',
    tempo: '3-1-3',
    load: 'Weight across the knees',
    frequency: { perWeek: 4 },
    bucket: 'couch',
    tissues: ['achilles-calf'],
  },
  {
    id: 'dl-knee-extension-isometric-band',
    exerciseId: 'knee-extension-isometric-band',
    sets: 5,
    durationSeconds: 45,
    displayAmount: '5 × 45 s @ ~70% effort',
    tempo: 'isometric',
    load: 'Band or ankle weight, seated',
    frequency: { perWeek: 'daily' },
    bucket: 'couch',
    tissues: ['quads', 'patellar-tendon'],
    notes: 'Tendon isometrics stay daily through a deload — they are analgesic, not load.',
  },
  {
    id: 'dl-ankle-eversion-band',
    exerciseId: 'ankle-eversion-band',
    sets: 3,
    reps: 15,
    displayAmount: '15 per direction',
    tempo: '2-1-2',
    load: 'Light band, seated',
    frequency: { perWeek: 4 },
    bucket: 'couch',
  },
  {
    id: 'dl-band-lateral-walk',
    exerciseId: 'band-lateral-walk',
    sets: 2,
    reps: 14,
    displayAmount: '12–15 steps per direction',
    tempo: '2-1-2',
    load: 'Mini loop band above the knees',
    frequency: { perWeek: 3 },
    bucket: 'quick',
    tissues: ['glutes'],
  },
  {
    id: 'dl-dead-bug',
    exerciseId: 'dead-bug',
    sets: 2,
    reps: 9,
    displayAmount: '8–10 per side',
    tempo: '3-1-3',
    load: 'Bodyweight',
    frequency: { perWeek: 3 },
    bucket: 'quick',
    tissues: ['trunk'],
  },
  {
    id: 'dl-single-leg-balance-eyes-closed',
    exerciseId: 'single-leg-balance-eyes-closed',
    sets: 3,
    durationSeconds: 30,
    displayAmount: '30 s per leg',
    tempo: 'isometric',
    load: 'Barefoot on the floor',
    frequency: { perWeek: 'daily' },
    bucket: 'quick',
    notes: 'Balance is unchanged in a deload — it is not the thing you are recovering from.',
  },
  {
    id: 'dl-y-balance-reach',
    exerciseId: 'y-balance-reach',
    sets: 2,
    reps: 5,
    displayAmount: '5 reaches per direction per leg',
    tempo: '3-0-3',
    load: 'Tape marks on the floor',
    frequency: { perWeek: 3 },
    bucket: 'quick',
  },
]

/**
 * The research doc's scheduling algorithm, R1–R27, condensed. The planner
 * implements a subset in code; this is the human-readable reference shown in
 * the UI so the rules the planner *doesn't* encode stay visible.
 */
export const sequencingRules: string[] = [
  'R1. Classify every planned item HARD or EASY. HARD = sport, heavy strength (upper or lower), plyometric/landing block, interval cardio. EASY = Zone 2, recovery walk, isometrics, band work, floor balance, mobility.',
  'R2. Cap HARD days at 4 per week. Absolute ceiling 5, and only in a week with no interval session and no plyometric block.',
  'R3. Never schedule 3 consecutive HARD days. Two in a row is allowed only when the second is a lift and the first is sport (or vice versa) — never sport on sport on sport.',
  'R4. No heavy lower-body strength on the calendar day before a sport day. Highest-priority rule: if it conflicts with anything below, it wins.',
  'R5. Heavy lower-body strength on the same day as sport is allowed and preferred — after play, ideally ≥2h after, never before.',
  'R6. Heavy lower-body strength the day after sport is allowed if the sport day was ≤90 minutes and there was no notable soreness on waking.',
  'R7. Minimum 48h between heavy lower-body sessions; 72h if the last one included new exercises, added load, or produced next-day soreness ≥3/10.',
  'R8. Plyometric and landing volume counts as lower-body load. Never the day before sport; never the same day as heavy lower-body strength beyond the warm-up dose.',
  'R9. Heavy upper-body strength has no restriction relative to sport days — it can go the day before basketball. It is the one lever that stays free.',
  'R10. While the right wrist is symptomatic: no loaded wrist extension, no loaded gripping at end range, no pushing on an extended wrist. Pressing goes to neutral-grip dumbbells, parallettes, or landmine; pulling uses a neutral grip. Wrist extensor isometrics are daily and are treatment, not training load.',
  'R11. Pickleball loads the wrist and elbow directly. In any week with 2+ pickleball sessions, drop loaded carries entirely.',
  'R12. Tendon isometrics can be done daily — on sport days, on rest days, twice a day if symptomatic. They are analgesic and low-load, and never count against the HARD-day budget.',
  'R13. Tendon HSR (heavy, slow, 6-second reps) counts as strength load. Calf/Achilles HSR goes inside the strength sessions, 2–3x/week, on non-consecutive days.',
  'R14. Isometrics 10–20 minutes before sport can be used deliberately for the PFPS knee and patellar tendon — the analgesic window runs roughly 45 minutes. Do not use this to mask a tendon that is actually flaring.',
  'R15. Anterior tibialis work while acute: isometrics only. No resisted dorsiflexion through range, no downhill or decline walking, no barefoot sprinting starts. Progress to banded dorsiflexion raises only once isometrics are pain-free at full effort.',
  'R16. Zone 2 is unrestricted. Any day including the day before sport, the same day as strength, or twice in a day. It is the volume filler.',
  'R17. Maximum one interval session per week. Zero in any week with 4 sport days.',
  'R18. Interval sessions must be ≥48h from a sport day on either side, and never within 24h of heavy lower-body strength. In practice: Sunday, or dropped.',
  'R19. Prefer non-impact modalities for interval work (Peloton, elliptical) until the tibialis anterior is fully quiet and PFPS is stable through a full sport week. Court conditioning shuttles are the last thing added, not the first.',
  'R20. If Peloton reproduces knee pain after cleat, float and saddle adjustment, switch to elliptical and revisit the fit. Do not push through a bike-fit problem — it is mechanical, not a fitness issue.',
  'R21. 4 sport days in a week → one heavy strength session only (the full-body Strength A), no interval session, tendon isometrics daily, the court warm-up before every session, Zone 2 only on the true off day. Sport is the training that week.',
  'R22. 5+ sport days → strength becomes a single ~20-minute maintenance dose (2 lower, 2 upper, tendon HSR), no plyometrics outside warm-ups, no intervals. Sustainable for about 2 weeks, not indefinitely.',
  'R23. 2 sport days → add the second strength session back plus one interval session, and add one long (60 min) Zone 2. This is the week where fitness actually gets built.',
  'R24. 0 sport days (travel, illness, injury pause) → strength 2–3x, Zone 2 4–5x, full tendon protocol, balance daily. The best available window for tendon work.',
  'R25. Every 4th week is a deload: cut strength volume ~40% (drop sets, keep load), no intervals, Zone 2 unchanged, sport unchanged. Non-negotiable at 49.',
  'R26. Progression cap: raise weekly training volume (total minutes + total hard sets) by no more than roughly 10% week to week, and avoid re-entry spikes after a layoff. Acute:chronic ratio thresholds are contested and are not a precise dial.',
  'R27. Return-from-pause ramp: first week back is 1 sport day at ~50% duration; second week 2 sport days; third week 3. No plyometric block and no intervals until the third week.',
]

export const strengthProgram: ProgramDef = {
  id: 'strength',
  name: 'Durability Strength',
  priority: 50,
  phases: [
    {
      id: 'ongoing',
      name: 'Ongoing',
      exitCriteria:
        'No exit — this program runs indefinitely. Switch to Deload every 4th week (R25), after any week with 4+ sport days (R21), or on two or more overreaching signs.',
      // Deload is entered on BAD signals or the calendar, never as a promotion.
      advanceProposals: false,
      items: ongoingItems,
      checkInQuestions: [
        {
          id: 'morning_soreness',
          label: 'Worst soreness in the first 20 min after waking (0–10)',
          type: 'pain0to10',
        },
        {
          id: 'settles_overnight',
          label: 'Did yesterday’s training pain settle to baseline by this morning?',
          type: 'yesNo',
        },
        {
          id: 'resting_hr_up',
          label: 'Resting HR ≥5 bpm above baseline for 3+ days?',
          type: 'yesNo',
        },
        {
          id: 'multiple_niggles',
          label: 'Multiple small niggles in different tissues at once?',
          type: 'yesNo',
        },
      ],
      redFlags: [
        'Sharp, localized pain that changes your gait or shooting mechanics, especially if it came on suddenly during a single movement.',
        'A pop or snap at the moment of injury, with swelling.',
        'Knee swelling within hours of activity, or a knee that gives way or locks.',
        'Calf pain that is one-sided, warm, and present at rest — rule out DVT before assuming tendon.',
        'Overreaching: resting heart rate 5–7 bpm above your morning baseline for 3+ consecutive days.',
        'Overreaching: sleep disruption on a normal schedule, particularly early waking, or a motivation drop specifically toward training you normally like.',
        'Overreaching: multiple small niggles appearing at once in different tissues — the classic masters pattern, meaning systemic recovery capacity is exceeded.',
        'Overreaching: warm-up feeling worse than usual and not improving 15 minutes in, or soreness lasting >72h after a session that used to take 48h.',
      ],
    },
    {
      id: 'deload',
      name: 'Deload week',
      entryCriteria:
        'Every 4th week; or reactively on any two overreaching signs; or automatically after a week with 4+ sport sessions (R21). Re-enter here at ~60% volume after any layoff >10 days.',
      exitCriteria:
        'One week. Return to Ongoing when morning soreness is back to baseline and resting HR is within 5 bpm of normal; rebuild over 2–3 weeks after a long layoff.',
      items: deloadItems,
      checkInQuestions: [
        {
          id: 'morning_soreness',
          label: 'Worst soreness in the first 20 min after waking (0–10)',
          type: 'pain0to10',
        },
        {
          id: 'resting_hr_normal',
          label: 'Resting HR back within 5 bpm of baseline?',
          type: 'yesNo',
        },
      ],
    },
  ],
  pregameItems: [
    {
      id: 'pg-court-dynamic-warmup',
      exerciseId: 'court-dynamic-warmup',
      sets: 1,
      durationSeconds: 720,
      displayAmount: '8–12 min',
      tempo: 'continuous',
      load: 'Court space',
      frequency: { perWeek: 'daily' },
      bucket: 'quick',
      notes:
        'Jog → hip openers/closers → lateral shuffles → walking lunges → build-up strides → defensive slides → two easy layup or dink sequences. Before every court session — that is the dose it was trialed at.',
    },
    {
      id: 'pg-knee-extension-isometric',
      exerciseId: 'knee-extension-isometric-band',
      sets: 5,
      durationSeconds: 45,
      displayAmount: '5 × 45 s @ ~70% effort',
      tempo: 'isometric',
      load: 'Band or ankle weight, seated',
      frequency: { perWeek: 'daily' },
      bucket: 'couch',
      alternates: ['pg-court-dynamic-warmup'],
      notes: 'Optional: 10–20 min before you leave, for the ~45-minute analgesic window on the PFPS knee (R14).',
    },
  ],
  postgameItems: [
    {
      id: 'post-calf-hsr',
      exerciseId: 'calf-raise-straight-knee',
      sets: 4,
      reps: 8,
      displayAmount: '4 × 6–8 reps (HSR tempo)',
      tempo: '3-0-3',
      load: 'Heavy — 6–15RM per the HSR wave',
      frequency: { perWeek: 2 },
      minSpacingDays: 2,
      bucket: 'workout',
      workoutSizes: ['S', 'M', 'L'],
      tissues: ['achilles-calf'],
      intensity: 'hard',
      notes:
        'Stacking the strength session onto the sport day is the preferred layout (R5) — lift after play, ideally ≥2h after. Tendon HSR rides along with it (R13).',
    },
  ],
}
