import type { CheckInQuestion, Exercise, ProgramDef, ProtocolItem } from './types'

/**
 * Tibialis anterior tendinopathy (right) — generated from
 * `docs/research/tibialis-anterior.md`. Acute rehab, four phases, top priority.
 *
 * The protocol is really four load-management principles (tendons respond to
 * load not rest · total load = training + daily life · the 24-hour rule ·
 * progress by capacity not calendar); the exercises are the delivery vehicle.
 * Daily-life and cardio guidance lives in `tibantNotes` below.
 */

export const tibantExercises: Record<string, Exercise> = {
  // ── Phase A — calm it down ──────────────────────────────────────────
  'ta-iso-dorsiflexion': {
    id: 'ta-iso-dorsiflexion',
    name: 'Isometric Dorsiflexion Hold',
    targetArea: 'Tib anterior tendon',
    cue: 'Steady pressure, not a squeeze — same effort at second 45 as at second 5.',
    instructions:
      'Sit with the leg out and loop a band over the top of the foot anchored ahead of you, or simply push the top of the right foot up into a couch leg, a table leg, or your other foot. Hold a steady mid-range pull-up effort for 45 seconds, five holds, ~2 minutes rest between.',
    whyItMatters:
      'Low-load, safe entry point that is analgesic for some people. Test it for a week — if a set of holds drops your pain, keep it; if it does nothing, move on to Phase B loading.',
    contextTag: 'couch',
    equipment: ['band'],
    commonMistakes: [
      'Going to end-range dorsiflexion — that often compresses the tendon under the retinaculum',
      'Ramping effort up and down instead of holding steady',
      'Going so hard that pain exceeds 3/10',
    ],
    progression:
      'Increase effort toward ~70% of max, then move the ankle angle toward more dorsiflexion, then move to banded dorsiflexion.',
    regression:
      'Drop to 20–30 second holds at 30% effort, or push into your other foot instead of a band so you control the resistance exactly.',
  },
  'ankle-pumps-pain-free': {
    id: 'ankle-pumps-pain-free',
    name: 'Pain-Free Ankle Pumps',
    targetArea: 'Ankle range',
    cue: 'Move inside the quiet zone — stop before the sharp edge.',
    instructions:
      'Seated or lying, slowly point and flex the foot through whatever range does not hurt. Purely circulatory and range-maintaining, not a strengthening exercise.',
    contextTag: 'couch',
    equipment: [],
    commonMistakes: ['Forcing through the painful end range', 'Going fast'],
    progression: 'Gradually reclaim range as pain allows.',
    regression: 'Smaller arc, fewer reps.',
  },
  'toe-tap-seated': {
    id: 'toe-tap-seated',
    name: 'Seated Toe Taps',
    targetArea: 'Tib anterior',
    cue: 'Heels glued, toes to shins.',
    instructions:
      'Sit with heels on the floor and lift just the forefoot and toes off the ground, then set them down under control. Zero external load — the lowest rung of the dorsiflexion ladder.',
    contextTag: 'couch',
    equipment: [],
    commonMistakes: ['Lifting the heel too', 'Bouncing'],
    progression: 'Slow the lowering to 3 seconds, then add a light ankle weight.',
    regression: 'One foot at a time, half range.',
  },
  'ta-self-massage': {
    id: 'ta-self-massage',
    name: 'Anterior Shin Self-Massage',
    targetArea: 'Tib anterior muscle belly',
    cue: 'Work the muscle belly, leave the tendon alone.',
    instructions:
      'Roll a ball or massage stick along the muscle belly of the tibialis anterior — the meaty part just lateral to the shin bone, upper two-thirds of the shin. Do not grind directly on the tender tendon at the front of the ankle.',
    contextTag: 'couch',
    equipment: ['massage-ball'],
    commonMistakes: [
      'Aggressive cross-friction on the acutely painful tendon — it provokes it; that is a chronic-case tool, not an acute one',
    ],
    progression: 'Add more pressure as tolerance improves.',
    regression: 'Hands only, light pressure.',
  },
  'short-foot': {
    id: 'short-foot',
    name: 'Short Foot / Arch Activation',
    targetArea: 'Foot intrinsics',
    cue: 'Dome the arch, keep the toes long and relaxed.',
    instructions:
      'Sit with the foot flat and, without curling the toes, draw the ball of the foot slightly toward the heel so the arch lifts a few millimetres. Hold 5 seconds.',
    whyItMatters:
      'Foot intrinsic strengthening is specifically named in the AAFP foot/ankle tendinopathy rehab guidance — a better-supported arch means less tib anterior work.',
    contextTag: 'couch',
    equipment: [],
    commonMistakes: ['Curling or clawing the toes', 'Lifting the big toe'],
    progression: 'Do it standing, then in single-leg stance.',
    regression: 'Use your hand to passively shape the arch first so you feel the target position.',
  },
  'gastroc-stretch-wall': {
    id: 'gastroc-stretch-wall',
    name: 'Wall Gastrocnemius Stretch',
    targetArea: 'Gastroc · calf',
    cue: 'Back heel nailed to the floor, hips forward, not down.',
    instructions:
      'Hands on the wall, right leg back, knee straight, heel down; lean in until you feel a stretch in the upper calf. Hold 30 seconds.',
    whyItMatters:
      'A stiff calf means the shin muscle has to work harder to get the foot up, so this directly reduces tib anterior demand.',
    contextTag: 'standing',
    equipment: [],
    commonMistakes: [
      'Letting the back heel rise',
      'Letting the arch collapse and the foot turn out',
    ],
    progression: 'Foot on a slant board or step edge.',
    regression: 'Seated towel stretch, or reduce the lean.',
  },
  'soleus-stretch-bent': {
    id: 'soleus-stretch-bent',
    name: 'Bent-Knee Soleus Stretch',
    targetArea: 'Soleus · Achilles',
    cue: 'Bend the knee toward the wall, keep the heel down.',
    instructions:
      'Same wall setup as the gastroc stretch, but bend the back knee slightly to shift the stretch to the lower calf and Achilles. Hold 30 seconds.',
    contextTag: 'standing',
    equipment: [],
    commonMistakes: ['Bending so much that the heel lifts'],
    progression: 'Elevate the forefoot on a book or step.',
    regression: 'Reduce depth.',
  },
  'quad-iso-wall-sit': {
    id: 'quad-iso-wall-sit',
    name: 'Wall Sit (PFPS Isometric)',
    targetArea: 'Quads',
    cue: 'Weight in the heels, knees tracking over the second toe.',
    instructions:
      'Back against a wall, slide down to roughly 30–60° of knee bend and hold 30–45 seconds, five holds. Mid-range knee angles are more comfortable in anterior knee pain than near-full extension or deep flexion.',
    contextTag: 'standing',
    equipment: [],
    commonMistakes: [
      'Going too deep and provoking the kneecap',
      'Knees falling inward',
      'Letting the heels lift — that loads the tib anterior; keep the whole foot down',
    ],
    progression: 'Deeper angle, longer hold, or a ball squeezed between the knees.',
    regression: 'Shallower angle, shorter hold.',
  },
  'glute-bridge': {
    id: 'glute-bridge',
    name: 'Double-Leg Glute Bridge',
    targetArea: 'Glutes',
    cue: 'Squeeze the glutes to lift, not the low back to arch.',
    instructions:
      'Lying on your back, knees bent and feet flat, drive through the heels and lift the hips until the body is a straight line from knee to shoulder.',
    whyItMatters:
      'The JOSPT patellofemoral pain guideline puts combined hip- and knee-targeted exercise at the centre of PFPS management, with hip work often preferred early.',
    contextTag: 'floor',
    equipment: ['mat'],
    commonMistakes: ['Overarching the lumbar spine', 'Pushing through the toes'],
    progression: 'Single-leg glute bridge, then add load.',
    regression: 'Smaller range of hip lift.',
  },
  'side-lying-hip-abduction': {
    id: 'side-lying-hip-abduction',
    name: 'Side-Lying Hip Abduction',
    targetArea: 'Glute medius',
    cue: 'Lead with the heel, keep the toes pointed straight ahead.',
    instructions:
      'Lie on your left side, body in a straight line, lift the right leg toward the ceiling with the toes pointing forward (not up), and lower slowly over 3 seconds.',
    contextTag: 'floor',
    equipment: ['mat'],
    commonMistakes: [
      'Rolling the pelvis backward',
      'Letting the toes turn up, which swaps glute med for hip flexors',
    ],
    progression: 'Ankle weight, then a band.',
    regression: 'Bend the knee to shorten the lever.',
  },
  clamshell: {
    id: 'clamshell',
    name: 'Clamshell',
    targetArea: 'Glute medius',
    cue: 'Pelvis stacked and still — only the knee moves.',
    instructions:
      'Side-lying, hips and knees bent ~45°, feet together, band above the knees; open the top knee without letting the pelvis roll back.',
    contextTag: 'floor',
    equipment: ['band', 'mat'],
    commonMistakes: ['Rocking the pelvis backward to fake range'],
    progression: 'Heavier band, or do it with the hips lifted (side plank clamshell).',
    regression: 'No band.',
  },

  // ── Phase B — progressive loading ───────────────────────────────────
  'ta-band-dorsiflexion': {
    id: 'ta-band-dorsiflexion',
    name: 'Banded Dorsiflexion (Slow)',
    targetArea: 'Tib anterior tendon',
    cue: 'Fight the band all the way back down — the return is the rep.',
    instructions:
      'Sit with the leg out, band anchored in front of you and looped over the top of the foot. From a toes-pointed start, pull the foot toward your shin over 3 seconds, hold 1 second, and let the band pull the foot back down over 3 seconds.',
    whyItMatters:
      'The slow lowering is the point — heavy-slow resistance matched eccentric-only protocols in Achilles tendinopathy with better adherence and satisfaction.',
    contextTag: 'couch',
    equipment: ['band'],
    commonMistakes: [
      'Letting the band snap the foot back down',
      'Using a band so heavy the tempo breaks',
      'Moving the whole leg instead of just the ankle',
    ],
    progression: 'Thicker band, then move to the seated weighted tib raise for a truly heavy load.',
    regression: 'Thinner band, reduce range, or drop back to seated toe taps.',
  },
  'ta-band-inversion-df': {
    id: 'ta-band-inversion-df',
    name: 'Banded Dorsiflexion + Inversion',
    targetArea: 'Tib anterior tendon',
    cue: 'Big toe up and toward the opposite knee.',
    instructions:
      'Same setup as banded dorsiflexion, but anchor the band to your outside so you pull the foot up and inward against it. This matches the tendon’s actual line of pull.',
    contextTag: 'couch',
    equipment: ['band'],
    commonMistakes: ['Rotating the whole leg at the hip', 'Letting the arch collapse'],
    progression: 'Thicker band, slower eccentric.',
    regression: 'Reduce range, thinner band, or do pure dorsiflexion only.',
  },
  'seated-weighted-tib-raise': {
    id: 'seated-weighted-tib-raise',
    name: 'Seated Weighted Toe Raise',
    targetArea: 'Tib anterior tendon',
    cue: 'Drive the toes to the ceiling and lower like you’re setting down glass.',
    instructions:
      'Sit on the couch with heels on the floor and a dumbbell or kettlebell resting across the top of the forefoot (a towel underneath helps). Lift the forefoot over 3 seconds, hold 1, lower over 3.',
    whyItMatters:
      'Your primary heavy loader — and it is fully couch-compatible, which is why it is the item most likely to actually get done.',
    contextTag: 'couch',
    equipment: ['dumbbell'],
    commonMistakes: [
      'Weight placed too far back near the ankle, which kills the lever and the load',
      'Heel lifting',
      'Going fast once the weight gets hard',
    ],
    progression:
      'Heavier dumbbell along the HSR curve — start near a 15-rep weight and build over 8–12 weeks toward a 6-rep-max load.',
    regression: 'Lighter weight, or back to banded dorsiflexion.',
  },
  'wall-tib-raise': {
    id: 'wall-tib-raise',
    name: 'Wall Tibialis Raise',
    targetArea: 'Tib anterior',
    cue: 'Heels pinned, pull the toes toward your kneecaps.',
    instructions:
      'Stand with your back and heels against a wall and the feet about a foot-length out in front. Keeping the heels planted, lift the toes and forefoot as high as you can, then lower slowly.',
    contextTag: 'standing',
    equipment: [],
    commonMistakes: [
      'Walking the feet too far out, which turns it into a hamstring stretch',
      'Leaning off the wall',
      'Dropping the toes fast',
    ],
    progression: 'Feet further from the wall, more reps, or a band around the forefoot.',
    regression: 'Feet closer to the wall, or fewer reps.',
  },
  'heel-stand-forefoot-lower': {
    id: 'heel-stand-forefoot-lower',
    name: 'Heel Stand with Slow Forefoot Lower',
    targetArea: 'Tib anterior tendon · eccentric',
    cue: 'Up with two, down with one, four full seconds.',
    instructions:
      'Stand on your heels with the forefoot lifted, then lower the forefoot to the floor over 4 seconds against gravity — up on both legs, down mostly on the right.',
    whyItMatters:
      'The eccentric-emphasis exercise; eccentric loading is recommended over concentric-only for foot and ankle tendinopathy.',
    contextTag: 'standing',
    equipment: [],
    commonMistakes: [
      'Dropping the last part of the range',
      'Holding a wall so tightly you unload the exercise',
    ],
    progression: 'Add a backpack, then do the lowering fully single-leg.',
    regression: 'Both legs on the lower, or shorten to a 2-second lower.',
  },
  'heel-walk': {
    id: 'heel-walk',
    name: 'Heel Walks',
    targetArea: 'Tib anterior',
    cue: 'Short steps, toes high, no slapping.',
    instructions:
      'Lift the toes and forefeet and walk forward on your heels with short, controlled steps for 30–45 seconds.',
    contextTag: 'standing',
    equipment: [],
    commonMistakes: [
      'Long strides',
      'Letting the forefoot slap down',
      'Doing it on hard tile in thin socks',
    ],
    progression: 'Longer duration, or carry light dumbbells.',
    regression: '15 seconds, or heel-standing in place instead of walking.',
  },
  'calf-raise-progression': {
    id: 'calf-raise-progression',
    name: 'Calf Raises, Double → Single Leg',
    targetArea: 'Gastroc · soleus',
    cue: 'Push through the big toe, don’t roll to the outside edge.',
    instructions:
      'Off the edge of a step, rise onto the toes over 3 seconds and lower below level over 3 seconds. Start double-leg and move to single-leg on the right once you can do 15 clean double-leg reps.',
    whyItMatters:
      'A weak calf changes your gait and dumps work onto the anterior compartment — 25 single-leg raises is a Phase B exit gate for exactly that reason.',
    contextTag: 'standing',
    equipment: ['step'],
    commonMistakes: [
      'Rolling onto the pinky-toe side',
      'Bouncing at the bottom',
      'Bending the knee to cheat the top',
    ],
    progression: 'Single leg → backpack load → build toward 25 reps single-leg.',
    regression: 'Flat floor instead of a step; hold a rail for support.',
  },
  'single-leg-balance': {
    id: 'single-leg-balance',
    name: 'Single-Leg Balance',
    targetArea: 'Proprioception',
    cue: 'Let the foot make small corrections — don’t lock it rigid.',
    instructions: 'Stand on the right leg with the arms relaxed and hold 30–45 seconds.',
    contextTag: 'standing',
    equipment: [],
    commonMistakes: [
      'Gripping constantly with the toes',
      'Holding the breath',
      'Propping against furniture',
    ],
    progression: 'Eyes closed → cushion or pillow → add head turns or a ball toss.',
    regression: 'Fingertip on a wall.',
  },
  'banded-lateral-walk': {
    id: 'banded-lateral-walk',
    name: 'Banded Lateral Walk',
    targetArea: 'Glute medius',
    cue: 'Stay low, keep the band tight even on the return step.',
    instructions:
      'Mini band just above the knees, quarter-squat position; step sideways 15 steps one way and 15 back, keeping constant band tension.',
    contextTag: 'standing',
    equipment: ['band'],
    commonMistakes: [
      'Standing up tall between steps',
      'Letting the trailing knee collapse inward',
      'Band at the ankles instead of above the knees — a different exercise with less glute med',
    ],
    progression: 'Heavier band, lower stance, band at the ankles as an addition.',
    regression: 'No band, or fewer steps.',
  },
  'sl-glute-bridge': {
    id: 'sl-glute-bridge',
    name: 'Single-Leg Glute Bridge',
    targetArea: 'Glutes',
    cue: 'Level hips — imagine a glass of water on your pelvis.',
    instructions:
      'Bridge as before but with one foot on the floor and the other leg extended or the knee hugged to the chest.',
    contextTag: 'floor',
    equipment: ['mat'],
    commonMistakes: [
      'Pelvis dropping on the free-leg side',
      'Pushing through the toes rather than the heel',
    ],
    progression: 'Foot elevated on a step, or a weight across the hips.',
    regression: 'Back to the double-leg glute bridge.',
  },
  // 'step-down-eccentric' is defined in strength.ts — the registry merges all
  // exercise maps, so ta-b-stepdown references the shared definition.
  'split-squat': {
    id: 'split-squat',
    name: 'Split Squat',
    targetArea: 'Quads · glutes',
    cue: 'Straight down, not forward — torso tall.',
    instructions:
      'Feet in a long stance, right foot forward; lower straight down until the back knee approaches the floor, then drive up. Add a rear-foot-elevated variation later.',
    contextTag: 'gym',
    equipment: ['dumbbell'],
    commonMistakes: [
      'Front knee travelling far past the toes, which shifts load onto the kneecap',
      'Stance too short',
      'Front heel lifting, which also loads the anterior shin',
    ],
    progression: 'Rear foot elevated → dumbbells → deeper range.',
    regression: 'Shorter range, hold a doorframe for balance.',
  },

  // ── Phase C — energy storage / plyometric prep ──────────────────────
  'ta-fast-band-dorsiflexion': {
    id: 'ta-fast-band-dorsiflexion',
    name: 'Fast Banded Dorsiflexion',
    targetArea: 'Tib anterior · rate of force',
    cue: 'Quick and rhythmic, like a metronome.',
    instructions:
      'Same as banded dorsiflexion but with a lighter band and fast, snappy reps for 20–30 repetitions.',
    whyItMatters:
      'Trains rate of force development in the muscle-tendon unit before you ask it to do the same job under bodyweight.',
    contextTag: 'couch',
    equipment: ['band'],
    commonMistakes: ['Using a heavy band and losing the speed', 'Letting range shrink to nothing'],
    progression: 'Slightly heavier band while keeping the speed; more reps.',
    regression: 'Back to slow tempo.',
  },
  'heavy-tib-raise': {
    id: 'heavy-tib-raise',
    name: 'Heavy Weighted Tib Raise',
    targetArea: 'Tib anterior tendon',
    cue: 'Six hard reps, still 3 seconds down on the last one.',
    instructions:
      'The Phase B seated tib raise loaded heavy for 6–8 reps. A tib bar is what this is for; a heavy dumbbell over the forefoot works fine.',
    contextTag: 'gym',
    equipment: ['dumbbell'],
    commonMistakes: [
      'Load so heavy the tempo collapses',
      'Adding weight faster than the 24-hour rule allows',
    ],
    progression: 'Add weight in small increments once 8 reps are clean and pain-free next morning.',
    regression: 'Back to the 10–15 rep load.',
  },
  'sl-calf-raise-loaded': {
    id: 'sl-calf-raise-loaded',
    name: 'Loaded Single-Leg Calf Raise',
    targetArea: 'Gastroc · soleus',
    cue: 'Full height at the top, full stretch at the bottom.',
    instructions:
      'Single-leg calf raise off a step edge holding a dumbbell or wearing a loaded backpack — 3 seconds up, 3 seconds down.',
    contextTag: 'gym',
    equipment: ['step', 'dumbbell'],
    commonMistakes: ['Partial range', 'Bouncing out of the bottom'],
    progression: 'More weight.',
    regression: 'Bodyweight, or double-leg.',
  },
  'pogo-hop-double': {
    id: 'pogo-hop-double',
    name: 'Double-Leg Pogo Hops',
    targetArea: 'Ankle stiffness · energy storage',
    cue: 'Bounce off the floor like it’s hot — minimal ground contact time.',
    instructions:
      'Small, fast, springy hops in place off the balls of the feet with the ankles kept stiff and the knees nearly straight.',
    whyItMatters:
      'Energy-storage loading is the mode you have to reintroduce before returning to any jumping sport.',
    contextTag: 'floor',
    equipment: [],
    commonMistakes: [
      'Squatting into every hop — that’s a jump, not a pogo',
      'Landing heavy and flat',
      'Doing them on concrete when a wood floor or thin mat is available',
    ],
    progression: 'More reps, then single-leg pogos.',
    regression: 'Smaller amplitude, fewer reps, or a hand on a countertop to unload.',
  },
  'pogo-hop-single': {
    id: 'pogo-hop-single',
    name: 'Single-Leg Pogo Hops',
    targetArea: 'Ankle stiffness · energy storage',
    cue: 'Stay tall and quiet — you should barely hear the landings.',
    instructions: 'The same springy hops in place, on the right leg only.',
    contextTag: 'floor',
    equipment: [],
    commonMistakes: ['Drifting forward across the room', 'Hip dropping on each landing'],
    progression: 'More reps, then hop forward/backward and side-to-side.',
    regression: 'Back to double-leg.',
  },
  'jump-rope': {
    id: 'jump-rope',
    name: 'Jump Rope',
    targetArea: 'Anterior shin · calf',
    cue: 'Wrists turn the rope, ankles do the work.',
    instructions: 'Continuous low-amplitude skipping, 30–45 seconds per set.',
    whyItMatters:
      'The bridge between pogos and court work — it loads the anterior shin in exactly the rhythmic way basketball does.',
    contextTag: 'sweat',
    equipment: ['jump-rope'],
    commonMistakes: ['Big high jumps', 'Landing on the heels', 'Going straight to 3-minute rounds'],
    progression: 'Longer sets, then single-leg or alternating-foot skipping.',
    regression: 'Shorter sets, or mime the movement without a rope.',
  },
  'lateral-bound': {
    id: 'lateral-bound',
    name: 'Lateral Bound and Stick',
    targetArea: 'Reactive landing',
    cue: 'Stick it and freeze — if you wobble, you bounded too far.',
    instructions:
      'Push off the left leg, bound sideways, land on the right and hold the landing for a full 2 seconds under control before going back.',
    whyItMatters:
      'Directly rehearses the pickleball and basketball side-step demand under supervision, and exposes knee valgus before a game does.',
    contextTag: 'gym',
    equipment: [],
    commonMistakes: [
      'Bounding for distance instead of for control',
      'Knee collapsing inward on landing',
      'Landing stiff-legged',
    ],
    progression: 'Longer bound, then continuous bounding without the stick.',
    regression: 'Shorter bound, or step-and-stick rather than bound-and-stick.',
  },
  'deceleration-drill': {
    id: 'deceleration-drill',
    name: 'Run-to-Stop Deceleration',
    targetArea: 'Tib anterior · eccentric',
    cue: 'Sink the hips to stop — don’t brake with the front foot.',
    instructions: 'Jog or run 10–15 yards, then stop over 2–3 steps and hold.',
    whyItMatters:
      'Deceleration is where the tibialis anterior does its hardest eccentric work in court sport, so it gets rehearsed deliberately before games do it for you.',
    contextTag: 'sweat',
    equipment: [],
    commonMistakes: [
      'Stopping on one hard stiff step',
      'Heel-jamming into the floor',
      'Doing this before the Phase C jog criterion is met',
    ],
    progression: 'Faster approach, shorter stopping distance, add a change of direction after.',
    regression: 'Walk-to-stop, then jog-to-stop over 5 steps.',
  },
  'decline-walk-loading': {
    id: 'decline-walk-loading',
    name: 'Controlled Decline Walking',
    targetArea: 'Tib anterior · eccentric',
    cue: 'Short, quick steps — let the whole foot land, don’t reach out with the heel.',
    instructions:
      'Walk downhill on a gentle grade — a treadmill at −3% or a mild street hill — for 3–5 minutes at a slow pace with short steps.',
    whyItMatters:
      'Downhill is the specific eccentric tib anterior stressor: the thing to avoid in Phase A and the thing to deliberately reintroduce in Phase C, because you cannot play a decelerating sport on a tendon that has never been re-exposed to it.',
    contextTag: 'sweat',
    equipment: ['treadmill'],
    commonMistakes: [
      'Long over-striding heel-first steps',
      'Steep grades too early',
      'Doing 20 minutes on day one',
    ],
    progression: 'Steeper grade, then longer duration, then normal walking speed.',
    regression: 'Flat walking only.',
  },
  'spanish-squat': {
    id: 'spanish-squat',
    name: 'Spanish Squat / Loaded Wall Sit (PFPS)',
    targetArea: 'Quads',
    cue: 'Shins vertical, let the band hold you back.',
    instructions:
      'Loop a heavy band around the back of both knees anchored behind you at knee height, lean back against the band and sit into a ~60° knee bend, holding 30–45 seconds. A weighted wall sit substitutes if you have no anchor.',
    contextTag: 'gym',
    equipment: ['band'],
    commonMistakes: [
      'Letting the knees drift forward past the toes',
      'Band anchored too high or too low',
    ],
    progression: 'Heavier band, longer holds, add a dumbbell held at the chest.',
    regression: 'Plain wall sit.',
  },

  // ── Phase D — return to play ────────────────────────────────────────
  'sport-stationary-skills': {
    id: 'sport-stationary-skills',
    name: 'Stationary Shooting / Dinking',
    targetArea: 'Skill exposure',
    cue: 'Feet stay home — this session is about touch, not movement.',
    instructions:
      'Free throws and set shots without chasing rebounds; pickleball dinking at the kitchen line without lateral movement. Skill exposure with essentially no deceleration load.',
    contextTag: 'sweat',
    equipment: ['court'],
    commonMistakes: ['"Just one game" creep', 'Chasing loose balls'],
    progression: 'Add a few steps between shots, then add the shuffle-and-cut drill.',
    regression: 'Wall practice or shadow swings only.',
  },
  'shuffle-cut-drill': {
    id: 'shuffle-cut-drill',
    name: 'Lateral Shuffle + Change of Direction',
    targetArea: 'Court movement',
    cue: 'Plant on a wide base and push off — don’t twist on a stuck foot.',
    instructions:
      'Cone drill: shuffle side to side, then plant and cut. Run it at 50% intensity in week 1, 80% in week 2, and full speed in week 3.',
    contextTag: 'sweat',
    equipment: ['cones'],
    commonMistakes: [
      'Going to full intensity in the first session',
      'Crossing the feet',
      'Ignoring a knee that starts talking',
    ],
    progression: 'Larger area, less rest, add a ball, then add reactive (unplanned) cues.',
    regression: 'Slower, smaller area, longer rest.',
  },
  'jump-landing-drill': {
    id: 'jump-landing-drill',
    name: 'Repeated Jump with Soft Landing',
    targetArea: 'Landing absorption',
    cue: 'Land like you’re trying not to wake someone downstairs.',
    instructions:
      'Countermovement jumps, focused on absorbing the landing through the hips and knees and landing quietly.',
    contextTag: 'gym',
    equipment: [],
    commonMistakes: ['Stiff-legged landings', 'Knees caving in', 'Landing on the heels'],
    progression: 'Single-leg landings, then landing off a low box, then jumping for a rebound.',
    regression: 'Back to double-leg pogo hops.',
  },
  'scrimmage-graded': {
    id: 'scrimmage-graded',
    name: 'Graded Scrimmage / Game Play',
    targetArea: 'Return to sport',
    cue: 'Set a timer before you start and honor it.',
    instructions:
      'Play to the graded return schedule. The rule that matters more than the schedule: 48 hours between court sessions until you have completed four weeks of graded return.',
    whyItMatters:
      'Doubles before singles in pickleball, and pickleball before basketball — less jumping, less full-court deceleration, shorter sprints.',
    contextTag: 'sweat',
    equipment: ['court'],
    commonMistakes: [
      'Playing "just one more game"',
      'Ignoring a 24-hour flare and playing again the next day',
    ],
    progression: 'Advance one week in the schedule when the previous week caused no flare.',
    regression: 'Drop back one week in the schedule after any flare.',
  },
  'maintenance-tib-load': {
    id: 'maintenance-tib-load',
    name: 'Maintenance Heavy Tib Raise',
    targetArea: 'Tib anterior tendon',
    cue: 'Two sessions a week, forever — this is the insurance policy.',
    instructions:
      'The Phase C heavy tib raise, kept at 2x/week indefinitely. Recurrence is common in this tendon if the biomechanical and capacity contributors are not addressed.',
    contextTag: 'gym',
    equipment: ['dumbbell'],
    commonMistakes: ['Stopping once it stops hurting'],
    progression: 'Keep adding load slowly over months.',
    regression: 'Drop to banded dorsiflexion during a busy stretch, but do something.',
  },
  'maintenance-hip-knee': {
    id: 'maintenance-hip-knee',
    name: 'Maintenance Split Squat + Hip Abduction',
    targetArea: 'Quads · glutes',
    cue: 'The knee program doesn’t end when the knee stops hurting.',
    instructions:
      'Continued hip- and knee-targeted strength — split squats plus banded hip abduction — the long-term backbone of the PFPS side of the program.',
    contextTag: 'gym',
    equipment: ['dumbbell', 'band'],
    commonMistakes: [
      'Dropping the hip work first — it is the part with the best evidence in early PFPS management',
    ],
    progression: 'Add load.',
    regression: 'Bodyweight only.',
  },
  'pre-game-iso': {
    id: 'pre-game-iso',
    name: 'Pre-Game Isometric Dorsiflexion Primer',
    targetArea: 'Tib anterior tendon',
    cue: 'Test it once — if it doesn’t help, drop it.',
    instructions:
      'Three 30-second banded isometric dorsiflexion holds before warming up. Use it only if you were an isometric "responder" in Phase A — the analgesic effect is real for some people and absent for others.',
    contextTag: 'standing',
    equipment: ['band'],
    commonMistakes: ['Doing them to full fatigue right before playing'],
    regression: 'Skip it and just warm up longer.',
  },
}

/**
 * Section 8 red flags. Note the night-pain nuance: mild night ache is a
 * *typical* feature of this tendinopathy, unlike most musculoskeletal problems.
 */
const tibantRedFlags: string[] = [
  'SAME DAY — Weakness lifting the foot or toes, foot drop, or the foot slapping the floor when you walk. Anterior tibial tendon rupture presents this way, and it also raises peroneal nerve palsy.',
  'SAME DAY — A palpable gap, dell, or depression along the tendon, or a new lump at the front-inner ankle.',
  'SAME DAY — Pain that suddenly stops while dorsiflexion weakness appears. Rupture can relieve the pain while destroying function; this is the trap.',
  'SAME DAY — Sudden onset during a forceful movement, with a pop.',
  'Numbness or tingling on the top of the foot, especially in the web space between the first and second toes (deep peroneal nerve / anterior tarsal tunnel).',
  'Exercise-brought-on tightness, swelling, or numbness in the shin that resolves with rest (chronic exertional compartment syndrome).',
  'Increasingly pinpoint tenderness on the shin bone itself, worse within each workout and worse workout to workout (tibial stress fracture).',
  'Inability to bear weight, or inability to bear weight persisting 1–2 weeks past onset.',
  'Hot, red, swollen ankle with fever or systemic illness, or worsening crepitus over the tendon.',
  'Night pain: mild night ache is NORMAL for this tendon and is part of the ordinary presentation. But severe, unremitting, or escalating night pain — or night pain with fever, weight loss, or a cancer history — warrants evaluation.',
  'No improvement at all after 2–3 weeks of consistent load management, or symptoms worsening despite reducing load.',
  'Swelling that is increasing rather than stable or improving.',
  'Still not right at 8–12 weeks — that is the point to get a clinical opinion rather than keep waiting.',
  'Men over 45 are a high-risk group for anterior tibial tendon rupture. Any true dorsiflexion weakness gets checked immediately.',
]

// ── Phase A — calm it down ────────────────────────────────────────────

const phaseAItems: ProtocolItem[] = [
  {
    id: 'ta-a-iso',
    exerciseId: 'ta-iso-dorsiflexion',
    sets: 5,
    durationSeconds: 45,
    displayAmount: '5 × 45s hold',
    tempo: 'Isometric, ~40–70% effort',
    load: 'Band, or push into a couch leg / your other foot',
    frequency: { perWeek: 'daily' },
    bucket: 'couch',
    tissues: ['tibant-tendon'],
    intensity: 'easy',
    notes: 'Twice daily, 7 days/week. ~2 min rest between holds. Isometrics need no spacing.',
  },
  {
    id: 'ta-a-pumps',
    exerciseId: 'ankle-pumps-pain-free',
    sets: 3,
    reps: 20,
    displayAmount: '20 reps',
    tempo: '2s up / 2s down',
    load: 'None',
    frequency: { perWeek: 'daily' },
    bucket: 'couch',
    alternates: ['ta-a-toetap'],
    tissues: ['tibant-tendon'],
    intensity: 'easy',
    notes: '2–3x daily. Circulatory and range-maintaining only.',
  },
  {
    id: 'ta-a-toetap',
    exerciseId: 'toe-tap-seated',
    sets: 3,
    reps: 20,
    displayAmount: '20 reps',
    tempo: '1-0-1',
    load: 'Bodyweight of the foot only',
    frequency: { perWeek: 'daily' },
    bucket: 'couch',
    alternates: ['ta-a-pumps'],
    tissues: ['tibant-tendon'],
    intensity: 'easy',
  },
  {
    id: 'ta-a-massage',
    exerciseId: 'ta-self-massage',
    sets: 1,
    durationSeconds: 90,
    displayAmount: '60–90s per tender area',
    tempo: 'Slow, sustained',
    load: 'Lacrosse ball or massage stick',
    frequency: { perWeek: 'daily' },
    bucket: 'couch',
    tissues: ['tibant-tendon'],
    intensity: 'easy',
    notes: 'Muscle belly only — never grind the acutely painful tendon.',
  },
  {
    id: 'ta-a-shortfoot',
    exerciseId: 'short-foot',
    sets: 3,
    reps: 10,
    displayAmount: '10 × 5s hold',
    tempo: 'Slow',
    load: 'None',
    frequency: { perWeek: 'daily' },
    bucket: 'couch',
    tissues: ['tibant-tendon'],
    intensity: 'easy',
  },
  {
    id: 'ta-a-gastroc',
    exerciseId: 'gastroc-stretch-wall',
    sets: 3,
    durationSeconds: 30,
    displayAmount: '30s hold',
    tempo: 'Static',
    load: 'Wall',
    frequency: { perWeek: 'daily' },
    bucket: 'quick',
    alternates: ['ta-a-soleus'],
    tissues: ['achilles-calf'],
    intensity: 'easy',
  },
  {
    id: 'ta-a-soleus',
    exerciseId: 'soleus-stretch-bent',
    sets: 3,
    durationSeconds: 30,
    displayAmount: '30s hold',
    tempo: 'Static',
    load: 'Wall',
    frequency: { perWeek: 'daily' },
    bucket: 'quick',
    alternates: ['ta-a-gastroc'],
    tissues: ['achilles-calf'],
    intensity: 'easy',
  },
  {
    id: 'ta-a-wallsit',
    exerciseId: 'quad-iso-wall-sit',
    sets: 5,
    durationSeconds: 40,
    displayAmount: '30–45s hold',
    tempo: 'Isometric',
    load: 'Wall',
    frequency: { perWeek: 'daily' },
    bucket: 'quick',
    tissues: ['quads'],
    intensity: 'easy',
    notes: 'The knee rehab does not pause because the ankle hurts.',
  },
  {
    id: 'ta-a-bridge',
    exerciseId: 'glute-bridge',
    sets: 3,
    reps: 12,
    displayAmount: '12 reps',
    tempo: '2-1-2',
    load: 'Bodyweight',
    frequency: { perWeek: 'daily' },
    bucket: 'quick',
    tissues: ['glutes'],
    intensity: 'easy',
  },
  {
    id: 'ta-a-hipabd',
    exerciseId: 'side-lying-hip-abduction',
    sets: 3,
    reps: 15,
    displayAmount: '12–15 per side',
    tempo: '2-1-3',
    load: 'Bodyweight → ankle weight',
    frequency: { perWeek: 'daily' },
    bucket: 'quick',
    alternates: ['ta-a-clam'],
    tissues: ['glutes'],
    intensity: 'easy',
  },
  {
    id: 'ta-a-clam',
    exerciseId: 'clamshell',
    sets: 3,
    reps: 15,
    displayAmount: '15 per side',
    tempo: '2-1-2',
    load: 'Mini band',
    frequency: { perWeek: 'daily' },
    bucket: 'quick',
    alternates: ['ta-a-hipabd'],
    tissues: ['glutes'],
    intensity: 'easy',
  },
]

// ── Phase B — progressive loading ─────────────────────────────────────

const phaseBItems: ProtocolItem[] = [
  {
    id: 'ta-b-band-df',
    exerciseId: 'ta-band-dorsiflexion',
    sets: 4,
    reps: 15,
    displayAmount: '12–15 reps',
    tempo: '3s up / 1s hold / 3s down',
    load: 'Band anchored ahead of you',
    frequency: { perWeek: 3 },
    minSpacingDays: 2,
    bucket: 'couch',
    alternates: ['ta-b-tibraise', 'ta-b-walltib'],
    tissues: ['tibant-tendon'],
    intensity: 'hard',
    notes: '3x/week, at least 48 hours apart — the heavy-slow-resistance dosing.',
  },
  {
    id: 'ta-b-band-inv',
    exerciseId: 'ta-band-inversion-df',
    sets: 3,
    reps: 15,
    displayAmount: '12–15 reps',
    tempo: '3-1-3',
    load: 'Band anchored to the outside',
    frequency: { perWeek: 3 },
    minSpacingDays: 2,
    bucket: 'couch',
    tissues: ['tibant-tendon'],
    intensity: 'hard',
  },
  {
    id: 'ta-b-tibraise',
    exerciseId: 'seated-weighted-tib-raise',
    sets: 4,
    reps: 12,
    displayAmount: '10–15 reps',
    tempo: '3-1-3',
    load: 'Dumbbell / kettlebell over the toes, or ankle weight',
    frequency: { perWeek: 3 },
    minSpacingDays: 2,
    bucket: 'couch',
    alternates: ['ta-b-band-df', 'ta-b-walltib'],
    tissues: ['tibant-tendon'],
    intensity: 'hard',
    notes: 'Primary heavy loader. Start near a 15-rep weight; build toward a 6RM over 8–12 weeks.',
  },
  {
    id: 'ta-b-walltib',
    exerciseId: 'wall-tib-raise',
    sets: 3,
    reps: 18,
    displayAmount: '15–20 reps',
    tempo: '2-1-3',
    load: 'Bodyweight, back against wall',
    frequency: { perWeek: 3 },
    minSpacingDays: 2,
    bucket: 'quick',
    alternates: ['ta-b-band-df', 'ta-b-tibraise'],
    tissues: ['tibant-tendon'],
    intensity: 'hard',
  },
  {
    id: 'ta-b-heelstand',
    exerciseId: 'heel-stand-forefoot-lower',
    sets: 3,
    reps: 10,
    displayAmount: '10 reps',
    tempo: '1s up / 4s down',
    load: 'Bodyweight → backpack',
    frequency: { perWeek: 3 },
    minSpacingDays: 2,
    bucket: 'quick',
    tissues: ['tibant-tendon'],
    intensity: 'hard',
    notes: 'Up with two legs, down with the right — the eccentric-emphasis item.',
  },
  {
    id: 'ta-b-heelwalk',
    exerciseId: 'heel-walk',
    sets: 3,
    durationSeconds: 40,
    displayAmount: '30–45s',
    tempo: 'Short controlled steps',
    load: 'Bodyweight',
    frequency: { perWeek: 3 },
    bucket: 'quick',
    tissues: ['tibant-tendon'],
    intensity: 'easy',
    notes: '45 seconds at ≤2/10 is a Phase B exit gate — this doubles as the test.',
  },
  {
    id: 'ta-b-calfraise',
    exerciseId: 'calf-raise-progression',
    sets: 3,
    reps: 15,
    displayAmount: '12–15 reps',
    tempo: '3s up / 3s down',
    load: 'Step edge, then backpack',
    frequency: { perWeek: 3 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    tissues: ['achilles-calf'],
    intensity: 'hard',
    notes: 'Build toward 25 single-leg reps on the right — a Phase B exit gate.',
  },
  {
    id: 'ta-b-balance',
    exerciseId: 'single-leg-balance',
    sets: 3,
    durationSeconds: 40,
    displayAmount: '30–45s per leg',
    tempo: 'Static, then eyes closed',
    load: 'None → pillow/cushion',
    frequency: { perWeek: 'daily' },
    bucket: 'quick',
    tissues: ['tibant-tendon'],
    intensity: 'easy',
  },
  {
    id: 'ta-b-latwalk',
    exerciseId: 'banded-lateral-walk',
    sets: 3,
    reps: 15,
    displayAmount: '15 steps each direction',
    tempo: 'Slow, controlled',
    load: 'Mini band above the knees',
    frequency: { perWeek: 3 },
    bucket: 'quick',
    tissues: ['glutes'],
    intensity: 'easy',
  },
  {
    id: 'ta-b-slbridge',
    exerciseId: 'sl-glute-bridge',
    sets: 3,
    reps: 12,
    displayAmount: '10–12 per side',
    tempo: '2-1-2',
    load: 'Mat',
    frequency: { perWeek: 3 },
    bucket: 'quick',
    tissues: ['glutes'],
    intensity: 'easy',
  },
  {
    id: 'ta-b-stepdown',
    exerciseId: 'step-down-eccentric',
    sets: 3,
    reps: 10,
    displayAmount: '8–10 reps',
    tempo: '4s lower',
    load: '4–8 in step',
    frequency: { perWeek: 3 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    tissues: ['quads'],
    intensity: 'hard',
    notes:
      'Stand on the RIGHT leg (the rehab side does the lowering work). PFPS gate — do not enter plyometrics with a reactive knee.',
  },
  {
    id: 'ta-b-splitsquat',
    exerciseId: 'split-squat',
    sets: 3,
    reps: 10,
    displayAmount: '8–10 per side',
    tempo: '3-1-1',
    load: 'Bodyweight → dumbbells',
    frequency: { perWeek: 3 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    tissues: ['quads', 'glutes'],
    intensity: 'hard',
    notes: '2–3x/week.',
  },
]

// ── Phase C — energy storage / plyometric prep ────────────────────────

const phaseCItems: ProtocolItem[] = [
  {
    id: 'ta-c-fastband',
    exerciseId: 'ta-fast-band-dorsiflexion',
    sets: 3,
    reps: 25,
    displayAmount: '20–30 fast reps',
    tempo: '1-0-1, snappy',
    load: 'Light band',
    frequency: { perWeek: 3 },
    bucket: 'couch',
    tissues: ['tibant-tendon'],
    intensity: 'easy',
    notes: 'Speed work, not load work — light band, no spacing requirement.',
  },
  {
    id: 'ta-c-heavytib',
    exerciseId: 'heavy-tib-raise',
    sets: 4,
    reps: 7,
    displayAmount: '6–8 reps',
    tempo: '3-1-3',
    load: 'Heavy dumbbell over the toes, or a tib bar',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    alternates: ['ta-c-fastband'],
    tissues: ['tibant-tendon'],
    intensity: 'hard',
    notes: 'Maintenance-level heavy tib loading, 2x/week with 48h between sessions.',
  },
  {
    id: 'ta-c-slcalf',
    exerciseId: 'sl-calf-raise-loaded',
    sets: 4,
    reps: 9,
    displayAmount: '8–10 per side',
    tempo: '3-0-3',
    load: 'Step edge + dumbbell or backpack',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    tissues: ['achilles-calf'],
    intensity: 'hard',
  },
  {
    id: 'ta-c-pogo-double',
    exerciseId: 'pogo-hop-double',
    sets: 3,
    reps: 20,
    displayAmount: '20 hops',
    tempo: 'Fast, stiff ankle, minimal knee bend',
    load: 'Bodyweight',
    frequency: { perWeek: 3 },
    minSpacingDays: 2,
    bucket: 'quick',
    alternates: ['ta-c-pogo-single', 'ta-c-rope'],
    tissues: ['tibant-tendon', 'achilles-calf'],
    intensity: 'hard',
    notes: 'Plyometrics 2–3x/week, never on back-to-back days.',
  },
  {
    id: 'ta-c-pogo-single',
    exerciseId: 'pogo-hop-single',
    sets: 3,
    reps: 13,
    displayAmount: '10–15 per leg',
    tempo: 'Fast',
    load: 'Bodyweight',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'quick',
    alternates: ['ta-c-pogo-double'],
    tissues: ['tibant-tendon', 'achilles-calf'],
    intensity: 'hard',
    notes: '3 × 15 on the right at ≤3/10 with no 24h flare is a Phase C exit gate.',
  },
  {
    id: 'ta-c-rope',
    exerciseId: 'jump-rope',
    sets: 4,
    durationSeconds: 40,
    displayAmount: '4 × 30–45s',
    tempo: 'Continuous, low bounce',
    load: 'Rope',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    alternates: ['ta-c-pogo-double'],
    tissues: ['tibant-tendon', 'achilles-calf'],
    intensity: 'hard',
  },
  {
    id: 'ta-c-bound',
    exerciseId: 'lateral-bound',
    sets: 3,
    reps: 6,
    displayAmount: '6 each side',
    tempo: 'Explosive out, 2s stick',
    load: '~6 ft of space',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    alternates: ['ta-c-decel'],
    tissues: ['tibant-tendon', 'quads'],
    intensity: 'hard',
  },
  {
    id: 'ta-c-decel',
    exerciseId: 'deceleration-drill',
    sets: 3,
    reps: 5,
    displayAmount: '5 reps',
    tempo: 'Fast in, 2s stick',
    load: '10–15 yd of space',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['L'],
    alternates: ['ta-c-bound'],
    tissues: ['tibant-tendon', 'quads'],
    intensity: 'hard',
  },
  {
    id: 'ta-c-decline',
    exerciseId: 'decline-walk-loading',
    sets: 2,
    durationSeconds: 240,
    displayAmount: '3–5 min',
    tempo: 'Slow, short steps',
    load: 'Treadmill at −3% or a gentle hill',
    frequency: { perWeek: 3 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    tissues: ['tibant-tendon'],
    intensity: 'hard',
    notes:
      '2–3x/week, 48h apart. The specific eccentric tib anterior stressor, reintroduced deliberately — decline walking is a genuine eccentric load on this tendon, so it counts as a hard day.',
  },
  {
    id: 'ta-c-spanish',
    exerciseId: 'spanish-squat',
    sets: 4,
    durationSeconds: 40,
    displayAmount: '30–45s hold',
    tempo: 'Isometric',
    load: 'Heavy band behind the knees, or a weighted wall sit',
    frequency: { perWeek: 3 },
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    tissues: ['quads'],
    intensity: 'easy',
    notes: '2–3x/week.',
  },
]

// ── Phase D — return to play ──────────────────────────────────────────

const phaseDItems: ProtocolItem[] = [
  {
    id: 'ta-d-court-shooting',
    exerciseId: 'sport-stationary-skills',
    sets: 1,
    durationSeconds: 1200,
    displayAmount: '15–20 min',
    tempo: 'Easy, no chasing',
    load: 'Ball or paddle',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    tissues: ['tibant-tendon'],
    intensity: 'hard',
    notes:
      'Weeks 1–2 of the graded return: 20 min stationary shooting or kitchen-line dinking, 2 sessions/week, 48h apart.',
  },
  {
    id: 'ta-d-court-drills',
    exerciseId: 'shuffle-cut-drill',
    sets: 4,
    durationSeconds: 25,
    displayAmount: '4 × 20–30s',
    tempo: '50% → 80% → game pace over 3 weeks',
    load: 'Cones',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    tissues: ['tibant-tendon', 'quads'],
    intensity: 'hard',
    notes:
      'Weeks 2–4: movement drills and layup lines at jog pace, then 1-on-0 cuts and half-court no-contact. 5 min at 80% with no 24h flare is a return-to-play checklist item.',
  },
  {
    id: 'ta-d-jumpland',
    exerciseId: 'jump-landing-drill',
    sets: 3,
    reps: 8,
    displayAmount: '8 reps',
    tempo: 'Explosive up, absorb quietly',
    load: 'Bodyweight',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    tissues: ['tibant-tendon', 'quads'],
    intensity: 'hard',
  },
  {
    id: 'ta-d-scrimmage',
    exerciseId: 'scrimmage-graded',
    sets: 1,
    durationSeconds: 2400,
    displayAmount: 'Per graded schedule',
    tempo: 'Game pace',
    load: 'Court',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['L'],
    alternates: ['ta-d-court-shooting'],
    tissues: ['tibant-tendon', 'quads'],
    intensity: 'hard',
    notes:
      'Wk3 rec doubles / half-court no-contact 30–40 min · wk4 3-on-3 or 2 games 40 min · wk5 45 min at ~half your normal game duration, 2–3x · wk6 one normal game, 2–3x · wk7 normal play 3x · wk8+ unrestricted but no back-to-back full-intensity days for another month. 48h between court sessions for the first 4 weeks; any flare drops you back one week.',
  },
  {
    id: 'ta-d-maint-tib',
    exerciseId: 'maintenance-tib-load',
    sets: 3,
    reps: 9,
    displayAmount: '8–10 reps',
    tempo: '3-1-3',
    load: 'Dumbbell or tib bar',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['S', 'M', 'L'],
    tissues: ['tibant-tendon'],
    intensity: 'hard',
    notes: '2x/week ongoing, on the days between court sessions. This one never stops.',
  },
  {
    id: 'ta-d-maint-hipknee',
    exerciseId: 'maintenance-hip-knee',
    sets: 3,
    reps: 9,
    displayAmount: '8–10 per side',
    tempo: '3-1-1',
    load: 'Dumbbells + band',
    frequency: { perWeek: 2 },
    minSpacingDays: 2,
    bucket: 'workout',
    workoutSizes: ['M', 'L'],
    tissues: ['quads', 'glutes'],
    intensity: 'hard',
    notes: '2x/week ongoing.',
  },
  {
    id: 'ta-d-pregame-iso',
    exerciseId: 'pre-game-iso',
    sets: 3,
    durationSeconds: 30,
    displayAmount: '3 × 30s',
    tempo: 'Isometric, moderate',
    load: 'Band',
    frequency: { perWeek: 'daily' },
    bucket: 'quick',
    tissues: ['tibant-tendon'],
    intensity: 'easy',
    notes: 'Before each court session. Only worth doing if you responded to isometrics in Phase A.',
  },
]

const painRuleQuestions: CheckInQuestion[] = [
  { id: 'pain_morning', label: 'Morning pain/stiffness on waking (0–10)', type: 'pain0to10' },
  {
    id: 'settles_24h',
    label: 'Back to baseline within 24h after every session?',
    type: 'yesNo',
  },
]

export const tibantProgram: ProgramDef = {
  id: 'tibant',
  name: 'Tib Ant Rehab (R)',
  priority: 10,
  phases: [
    {
      id: 'phaseA',
      name: 'Phase A — Calm it down',
      entryCriteria:
        'Acute anterior ankle / medial midfoot pain, tender to touch over the tendon, with pain on resisted dorsiflexion or uphill and stair walking. Baseline walking pain >3/10, or pain that flares for more than 24 hours after ordinary activity (an "irritable" tendon).',
      exitCriteria:
        'All must be true: pain ≤3/10 during a 15-minute flat walk in modified footwear; morning pain/stiffness improving week over week (lower on day 7 than day 1); 5 × 45s isometric dorsiflexion holds completed at ≤3/10 with no next-morning flare; no swelling increase, no new numbness or weakness. Typically 7–14 days. Sport: zero. Cardio: elliptical, or an easy Peloton spin after the cleat fix.',
      items: phaseAItems,
      checkInQuestions: [
        { id: 'pain_walk15', label: 'Pain during a 15-min flat walk (0–10)', type: 'pain0to10' },
        ...painRuleQuestions,
        {
          id: 'morning_improving',
          label: 'Morning stiffness lower than a week ago?',
          type: 'yesNo',
        },
        {
          id: 'iso_tolerated',
          label: '5 × 45s isometric holds at ≤3/10, no next-morning flare?',
          type: 'yesNo',
        },
        {
          id: 'swelling_numbness',
          label: 'Free of new swelling, numbness, or weakness?',
          type: 'yesNo',
        },
      ],
      redFlags: tibantRedFlags,
    },
    {
      id: 'phaseB',
      name: 'Phase B — Progressive loading',
      entryCriteria: 'Passed all Phase A exit criteria.',
      exitCriteria:
        'All must be true: pain ≤2/10 during a 30-minute continuous flat walk with no next-morning increase; 45-second heel walk at ≤2/10; 15 slow (3s up / 3s down) weighted seated tib raises at the same load on both legs, right ≤3/10 and not visibly weaker; 25 single-leg calf raises on the right; stairs up and down at normal pace at ≤2/10; knee eccentric step-down at ≤2/10. Typically 3–5 weeks. Heavy loading 3x/week at least 48h apart. Sport: still zero.',
      items: phaseBItems,
      checkInQuestions: [
        { id: 'pain_walk30', label: 'Pain during a 30-min flat walk (0–10)', type: 'pain0to10' },
        { id: 'pain_heelwalk', label: 'Pain during a 45s heel walk (0–10)', type: 'pain0to10' },
        {
          id: 'pain_stairs',
          label: 'Pain on stairs up and down at normal pace (0–10)',
          type: 'pain0to10',
        },
        { id: 'pain_stepdown', label: 'Knee pain on eccentric step-down (0–10)', type: 'pain0to10' },
        ...painRuleQuestions,
        {
          id: 'tibraise_equal',
          label: '15 slow weighted tib raises at the same load both sides?',
          type: 'yesNo',
        },
        { id: 'calf_25', label: '25 single-leg calf raises on the right?', type: 'yesNo' },
      ],
      redFlags: tibantRedFlags,
    },
    {
      id: 'phaseC',
      name: 'Phase C — Energy storage',
      entryCriteria:
        'Passed all Phase B exit criteria, and able to jog 5 minutes on flat ground at ≤2/10 with no next-day flare.',
      exitCriteria:
        'All must be true: 10-minute continuous flat jog at ≤2/10 with no 24h flare; 3 × 20 double-leg and 3 × 15 single-leg pogo hops on the right at ≤3/10, no 24h flare; jump rope 4 × 45s at ≤2/10; lateral bound and stick 6 each side, landings controlled, no knee valgus collapse, ≤2/10 at ankle and knee; single hop and triple hop for distance both ≥90% limb symmetry index; 3–5 minutes of controlled decline walking at ≤2/10. Typically 2–3 weeks. Plyometrics 2–3x/week, never back-to-back days. Sport: still no games.',
      items: phaseCItems,
      checkInQuestions: [
        { id: 'pain_jog10', label: 'Pain during a 10-min flat jog (0–10)', type: 'pain0to10' },
        {
          id: 'pain_pogo',
          label: 'Pain during pogo hops, double and single leg (0–10)',
          type: 'pain0to10',
        },
        {
          id: 'pain_decline',
          label: 'Pain during 3–5 min of decline walking (0–10)',
          type: 'pain0to10',
        },
        ...painRuleQuestions,
        { id: 'rope_ok', label: 'Jump rope 4 × 45s at ≤2/10?', type: 'yesNo' },
        {
          id: 'bound_control',
          label: 'Lateral bound and stick ×6/side, controlled, no knee valgus?',
          type: 'yesNo',
        },
        {
          id: 'hop_symmetry',
          label: 'Single and triple hop for distance both ≥90% of the left?',
          type: 'yesNo',
        },
      ],
      redFlags: tibantRedFlags,
    },
    {
      id: 'phaseD',
      name: 'Phase D — Return to play',
      entryCriteria:
        'Passed all Phase C exit criteria including the ≥90% hop symmetry gate, plus the full return-to-play checklist: no morning stiffness for 7 consecutive days, palpation pain ≤2/10, 25 single-leg calf raises, a 45-second heel walk at ≤2/10, no dorsiflexion weakness whatsoever, single-leg squat to 60° without the knee collapsing in, and play-tension laces with no tendon pain.',
      exitCriteria:
        'Two consecutive weeks of full-intensity play at your normal frequency (3+ days/week) with pain ≤2/10 during and no next-morning increase, no compensatory limp and no lace-loosening mid-game. Graded schedule: wk1 20 min stationary skills ×2 · wk2 30 min shooting + light dribbling or half-speed rallies ×2 · wk3 30–40 min movement drills / rec doubles ×2 · wk4 40 min 3-on-3 or 2 games ×2 · wk5 45 min half-length scrimmage ×2–3 · wk6 one normal game ×2–3 · wk7 normal play ×3 · wk8+ unrestricted. 48h between court sessions for the first 4 weeks; any flare drops you back one week, two flares at the same week sends you back to Phase C loading for two weeks. Maintenance loading 2x/week forever.',
      items: phaseDItems,
      checkInQuestions: [
        { id: 'pain_play', label: 'Pain during play (0–10)', type: 'pain0to10' },
        {
          id: 'pain_next_morning',
          label: 'Pain the morning after a court session (0–10)',
          type: 'pain0to10',
        },
        ...painRuleQuestions,
        {
          id: 'two_weeks_full',
          label: 'Two straight weeks of full-intensity play at normal frequency?',
          type: 'yesNo',
        },
        {
          id: 'no_limp',
          label: 'No limp and no lace-loosening mid-game?',
          type: 'yesNo',
        },
        {
          id: 'maintenance_running',
          label: 'Maintenance loading 2x/week in place?',
          type: 'yesNo',
        },
      ],
      redFlags: tibantRedFlags,
    },
  ],
  pregameItems: [
    {
      id: 'ta-pg-iso',
      exerciseId: 'pre-game-iso',
      sets: 3,
      durationSeconds: 30,
      displayAmount: '3 × 30s',
      tempo: 'Isometric, moderate',
      load: 'Band',
      frequency: { perWeek: 'daily' },
      bucket: 'quick',
      tissues: ['tibant-tendon'],
      intensity: 'easy',
      notes: 'Only if you were an isometric responder. Never to fatigue right before playing.',
    },
    {
      id: 'ta-pg-heelwalk',
      exerciseId: 'heel-walk',
      sets: 2,
      durationSeconds: 30,
      displayAmount: '2 × 30s',
      tempo: 'Short controlled steps',
      load: 'Bodyweight',
      frequency: { perWeek: 'daily' },
      bucket: 'quick',
      tissues: ['tibant-tendon'],
      intensity: 'easy',
      notes: 'Warm the shin before court work.',
    },
  ],
  postgameItems: [
    {
      id: 'ta-post-massage',
      exerciseId: 'ta-self-massage',
      sets: 1,
      durationSeconds: 90,
      displayAmount: '60–90s per tender area',
      tempo: 'Slow, sustained',
      load: 'Lacrosse ball or massage stick',
      frequency: { perWeek: 'daily' },
      bucket: 'couch',
      tissues: ['tibant-tendon'],
      intensity: 'easy',
      notes: 'Muscle belly only. Log tomorrow morning’s pain — that number is the 24-hour rule.',
    },
  ],
}

/**
 * Daily-life and cardio guidance from sections 5–6 of the research doc. These
 * matter more than the exercises in the first two weeks, because your legs do
 * vastly more walking than rehab. Rendered on the program card.
 */
export const tibantNotes: {
  loadManagement: string[]
  cardioByPhase: Record<string, string>
  pelotonFix: string[]
} = {
  loadManagement: [
    'Skip-lacing is the highest-leverage change. Skip the eyelet pair directly over the tender spot, or use a window lacing pattern to bridge it — lace compression under the extensor retinaculum is a common primary cause, and lacing changes alone can substantially reduce symptoms in early cases.',
    'Check every pair you actually wear: basketball high-tops are the worst offender, plus work boots, hiking boots, ski boots, and running shoes with a stiff tongue. A tongue pad or folded washcloth spreads pressure off the sore point.',
    'Shoe characteristics that help: firm supportive upper, 8–12 mm heel-to-toe drop, padded tongue, good lateral stability. Avoid zero-drop and minimalist shoes in the acute phase — less drop means more dorsiflexion demand.',
    'Phase A: cut daily step count by a third to a half and hold it there for the week. Break walks into short bouts and stay under the 15-minute continuous threshold you are testing against. Phase B: rebuild ~10% per week under the 24-hour rule.',
    'Take shorter steps at a slightly quicker cadence. Overstriding with a hard heel strike maximizes the eccentric demand on this tendon.',
    'Phase A: avoid hills entirely, take stairs slowly one at a time with a handrail, take the elevator when there is a choice. Phase B: stairs at normal pace once flat walking is ≤2/10; hills last. Phase C: reintroduce decline deliberately as an exercise, not accidentally as a commute.',
    'Avoid in Phase A: all court sport and running, jumping and jump rope, deep squats/lunges that force end-range dorsiflexion, StairMaster and incline treadmill, kneeling on the tops of the feet, and cross-friction massage on the acutely painful tendon.',
    'Do not go barefoot on hard floors all day in Phase A — slippers or a supportive house shoe beats a stone kitchen floor.',
    'Corticosteroid injection into or around this tendon: ask specifically about rupture risk. Chronic steroid exposure is a documented risk factor for anterior tibial tendon rupture, and men over 45 are the highest-risk group.',
    'Cold 10–15 min over the front of the ankle helps in the first few days. Use NSAIDs/acetaminophen for a few days, not weeks — they may interfere with tissue remodeling.',
  ],
  cardioByPhase: {
    phaseA:
      'Elliptical is the best first choice: 10–20 min, low resistance, no incline, feet flat, straps loose or off. Peloton seated at 85–95 rpm and low resistance for 15–20 min, but only with the cleat fix below. Swimming with a pull buoy is fine. No rowing erg (deep loaded dorsiflexion at the catch), no stair climber, no incline treadmill, no running, no jump rope. Walking as cardio: short flat bouts only.',
    phaseB:
      'Elliptical building to 30–45 min with resistance. Peloton seated 30–45 min; out-of-saddle work only in short bouts late in the phase. Flat walking building ~10%/week. Rowing erg with a shorter slide and a higher foot-stretcher setting. Still no running, jump rope, stair climber, or incline treadmill.',
    phaseC:
      'Full elliptical, Peloton including intervals and standing climbs, rowing, and swimming. Flat running restarts at 5 minutes. Jump rope is programmed in the Phase C table. Stair climber and low-grade incline treadmill only cautiously.',
    phaseD: 'Full range, everything unrestricted — including stair climber and incline treadmill.',
  },
  pelotonFix: [
    'Confirm you are on 9° red Delta cleats, not 0° black. If you are on black or 6°, this is a $20 fix and it is step one.',
    'Self-select the rotation angle: loosen the three cleat bolts until the cleat turns under hand pressure, pedal easily for 30–60 seconds letting the foot find its own angle, then unclip without twisting and tighten. Ride 10 minutes; adjust a few degrees at a time.',
    'Float lets the heel swing within a range centered on where the cleat is bolted — it does not center you at your natural angle. Bolt the cleat so your natural toe-out sits in the middle of the float range, not at its stop.',
    'If toe-out swings your heel into the crank arm, move the cleat toward the inside edge of the shoe and/or add a few millimetres of pedal spacers to widen the stance.',
    'Move the cleat rearward in 2–3 mm steps. Forefoot cleat position drives a quad-dominant stroke associated with kneecap pain; rearward shifts work to the hips and lowers ankle-stabilizer demand.',
    'The nuclear option: dual-function toe cages bolt onto the Peloton pedals so you can ride in sneakers at whatever foot angle you like. Keep the cage strap loose so it does not press on the front of the ankle. For rehab cardio the lost efficiency does not matter.',
    'Do not deliberately "pull up" on the upstroke — that is the exact phase where the tib anterior is active. Push down and let the other leg come around. Higher cadence with less resistance is easier on the shin than low-cadence grinding.',
  ],
}
